### ISSUE TITLE
hotcrp does not work with remote mysql server

### ISSUE THREAD

**Issue by mdrumond** [kohler/hotcrp#103]
Hi,

I am not quite sure this is a valid use case, but hotcrp will fail to create and access the databases if the mysql server is not located on the same machine as hotcrp. The root cause is the user creation script creates users only for `localhost` and its aliases.

You can quickly reproduce this by using a linking 2 docker containers, one with mysql (I tried the `mysql:5.6` container) and another with hotcrp, and running the following command in the hotcrp container:

```
./lib/create_user.sh --user=root --password=root --host=sql_container_name --port=3306
```

The script will create the user, but fail to create the databases. with the following error:

`ERROR 1045 (28000): Access denied for user 'new_username'@'ip_of_local_machine' (using password: YES)`

Where `new_username` is the newly created user and `ip_of_local_machine` is the ip of the local machine.

If this is indeed intended behavior, please update the documentation to reflect it.

If needed, you can contact me and I will share my private repo where you can reproduce the error with docker in a couple command.

**Comment by samguyer** [comment]
Hi Paulo

I have been able to get hotcrp running with a remote MySQL server. I had to
modify the createdb script a little, but it does work. I'll send you
another email with the details.

-Sam

**Comment by kohler** [comment]
I'm interested in the createdb changes @samguyer, and I'm also interested in the private repo—thanks for doing the work to create a replicable test case.

**Comment by mdrumond** [comment]
@kohler: Thank you very much for taking a look at this.
I added you to my repo. You want the following commit:
https://github.com/mdrumond/isca-2018/commit/0675335e61c032d8bcdfe3acae6b698e83c224f8

To reproduce the error, in a machine with docker (I am on Mac OS):
```bash
cd $ISCA_2018_ROOT
./manage_docker.sh build
./manage_docker.sh start
```

This will create 2 containers linked to each other, one with mysql and another with hotcrp in it. The hotcrp container sees the mysql container  with `sql` as the hostname. After starting the containers, you should find yourself in a bash inside the `hotcrp` container. There you should  run the follwing commands:
```bash
cd /hotcrp
./lib/createdb.sh --user=root --password=root --host=sql --port=3306
```

@samguyer: Thank you very much, I appreciate the script. For now I have converged to a solution with a single container, but I would like to have 2 containers.

**Comment by samguyer** [comment]
In my case, my department already has a MySQL server, and they create the user and database for me. I don't have admin level permissions, so the createdb script fails when it tries to check if the user and database exist (regardless of whether I tell the script not to). I just commented out the tests and forced createdb and createuser to false. I'm not sure what the "right" solution is in this case.

**Comment by oldphart4** [comment]
Our standard setup separates websites and web applications from backend databases by locating databases VMs on high performance hardware.  As such we need to be able to create the database(s) on this separate platform.

We have done this but hotcrp is not able to access the remote database even after configuring dbHost in options.php.  Running a mysql command line login works from the same machine.  Mysterious.

**Comment by kohler** [comment]
Found the problem. As part of default-off security, HotCRP explicitly configures the database to only allow access the HotCRP user access from localhost.

As of 161bf712274957da4f33bb3dd584b0ba6650312b a new `--grant-host` argument allows the `lib/createdb.sh` caller to specify other hosts for which access should be allowed.
