### ISSUE TITLE
Show conflict delta in meeting tracker

### ISSUE THREAD

**Issue by ericbodden** [kohler/hotcrp#104]
I am using a payed-for installation of HotCRP for ISSTA'18.

The meeting tracker currently shows the conflicts next to every paper. For the PC meeting it would be even more helpful, however, if HotCRP computed and showed also the delta, i.e., the people who have to come back into the room and the people who additionally have to leave the room, compared to the conflicts of the previous paper. Can this be enabled in HotCRP already? And if not, could this feature be added?

**Comment by kohler** [comment]
Hi Eric, FYI, I got around to this, and here is an example display you would now see.

![image](https://user-images.githubusercontent.com/410647/51284241-ddf4de00-19b8-11e9-823e-7bacbacd887f.png)

* Newly-conflicted PC members get a star (hopefully intuitive)
* No-longer-conflicted PC members are in a separate list
* PC tags are reflected in the visual
* If a tracker is restricted to a PC subset, such as “heavy PC”, then only heavy PC members show up in the conflict lists

Thanks for the request.
Eddie

**Comment by kohler** [comment]
I tried that and think it's better this way.

**Comment by kohler** [comment]
I may change my mind though ;)

**Comment by ericbodden** [comment]
You can make it yet another option :P


--
Sent from my mobile
________________________________
Von: Eddie Kohler <notifications@github.com>
Gesendet: Donnerstag, 17. Januar 2019 18:41
An: kohler/hotcrp
Cc: Eric Bodden; Author
Betreff: Re: [kohler/hotcrp] Show conflict delta in meeting tracker (#104) 

I may change my mind though ;)
