### ISSUE TITLE
Affiliation doesn't show up in downloaded PC Info

### ISSUE THREAD

**Issue by stevenjswanson** [kohler/hotcrp#107]
From  `https://nvmw2018.hotcrp.com/users?t=pc`, I get 

![image](https://user-images.githubusercontent.com/9068765/29491896-0eef50ce-851f-11e7-8e66-da8664ae65fd.png)

but clicking "go", gives me this:

![image](https://user-images.githubusercontent.com/9068765/29491904-2d9e9f98-851f-11e7-8fc6-ebe9ad852af8.png)

**Comment by kohler** [comment]
Fixed in ef40f96e92edab2318bdb71f81e5674ff83b8936, thanks for the report.
