### ISSUE TITLE
JSON paper data export does not include accepted/rejected status

### ISSUE THREAD

**Issue by stevenjswanson** [kohler/hotcrp#108]
It would be nice if the json output included the decision of the paper.  We have "accepted for poster" and "accepted for talk" and if this information were in the JSON, then we could very easily upload all the paper/poster information to our conference web site.

Example of problem:

This paper is accepted:  https://nvmw2018.hotcrp.com/paper/1

But it shows up as "submitted" in json output.

~~~
{
    "pid": 1,
    "title": "foo",
    "status": "submitted",
    "submitted": true,
    "submitted_at": 1503113041,
    "authors": [
        {
            "email": "swanson@cs.ucsd.edu",
            "first": "Steven",
            "last": "Swanson",
            "affiliation": "chrome",
            "contact": true
        },
        {
            "email": "steven.swanson@gmail.com",
            "first": "Firefox",
            "last": "swanson",
            "affiliation": "firefox"
        }
    ],
    "abstract": "ngtdh",
    "submission": {
        "mimetype": "application\/pdf",
        "hash": "sha2-291187490601bebdb53823cbeb777a5a309d5ec8934f3f82a1ec7802e08cd44e",
        "timestamp": 1503113041,
        "size": 87425,
        "content_file": "nvmw2018-paper1.pdf"
    },
    "pc_conflicts": {
        "swanson@cs.ucsd.edu": "author"
    }
}
~~~

In CSV output it shows up as "accepted":

![image](https://user-images.githubusercontent.com/9068765/29785748-99a9557e-8bdd-11e7-90d4-cdcd439d0675.png)

**Comment by kohler** [comment]
I've updated this, thanks for the request.
