### ISSUE TITLE
Emailing reviews on conflicted papers to TPC chairs 

### ISSUE THREAD

**Issue by Theophilusbenson** [kohler/hotcrp#109]
I've setup HotCRP.com to "Notify PC chairs of newly submitted reviews by email".  Today I got a review on a conflicted paper.

**Comment by kohler** [comment]
Hi Theo,

I actually ended up removing this feature b/c it wasn't good at handling conflicts. As a chair, you can now *individually* elect to receive notifications about reviews and comments on *every* submission, on the profile page. Mails sent that way should be correctly filtered when there are chair conflicts.

Eddie
