### ISSUE TITLE
ipaddr field is too small for full ipv6 address

### ISSUE THREAD

**Issue by wom-bat** [kohler/hotcrp#112]
The ipaddr field in the ActionLog table needs to be 39 characters wide, not 32, to cope with a full ipv6 address.  See screenshot below.

![screenshot_2017-11-08_08-07-10](https://user-images.githubusercontent.com/2782095/32518629-464b8406-c45e-11e7-9c41-6df1b8bdb269.png)

**Comment by kohler** [comment]
Thanks for the fix. I think actually though we should probably drop the ipaddr altogether—has it ever been useful for anything?

**Comment by kohler** [comment]
Fixed.
