### ISSUE TITLE
Content-Security-Policy prevents in-line javascript running.

### ISSUE THREAD

**Issue by wom-bat** [kohler/hotcrp#114]
Our admins set the Content-Security-Policy header fairly strictly.  In particular, script-src is set to 'self'.
This breaks changing passwords, amongst other things.

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-4axHYYUuP6AaFt7n7mZSmG/QXwhETlGfeR7D8yDCAro='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by kohler** [comment]
Your admins are assholes.

**Comment by wom-bat** [comment]
They're not that bad -- I managed to get them to change it.  But to prevent problems in future it'd be worth providing a nonce, or not using in-line javascript.

**Comment by kohler** [comment]
disbhjfighuajodkpscmvjdfbnghijworfdksmljfbghijworkmflsdcjbshijogkamfdlsjnfjiobmwklgesncjmdfkwjgqnwifomdslkvnbfjoqmgwlkdsnjfmqgkwnfeomcklnfjoigqmflkwencjovifmklgqnwefojicmlkfnbsjogqirwfmlekcndjoivfmklqgfewnojicmklfnbgqjoiwfemlckbfnsjogqmlfwekncjokmlfkgqnfjewoikmlcknfjoigqfmelwkcndsjvfkmlgqnfehojidmklsnbhgqjiofwem

**Comment by kohler** [comment]
That's like multiple days of low-value work. Patches are welcome though

**Comment by wom-bat** [comment]
I think the simplest thing to do at this point is to document the need for the Apache CSP setting in Readme.md.  I'll brew up a patch.

**Comment by kohler** [comment]
Because I am not always able to control what I am interested in, I committed thousands of lines of changes, there are no more `onclick`/etc. handlers, and if you set `$Opt["contentSecurityPolicy"] = true`, scripts will be served with a nonce.

I look forward to an expenses-paid trip to Australia to give a talk or something :)
