### ISSUE TITLE
What is hotlist-info and why does it get very large?

### ISSUE THREAD

**Issue by rfonseca** [kohler/hotcrp#120]
I was getting Apache to deny some requests because of header size limit exceeded. The limit in Apache AFAIK is 8K by default. It seems the main culprit is the hotlist-info cookie.

At the bottom I pasted an example of such cookie from an HTTP header dump. In one case this cookie was repeated. The ids are the ids of submissions (e.g., 64605995). 

I seem to have solved the problem by increasing the limit of the request in Apache (Apache 2) by adding the directive:

`LimitRequestFieldSize 32768`

But the question remains: what is hotlist-info and why does it get very large?

Thanks!

Cookie: hotlist-info=%7B%22ids%22%3A%2261534452'64605995'68050654'68250328'68849043'72724523'72845428'72942180'73141729'73185194'73301097'73354643'73390160'73618060'73632485'73654592'73720662'73725496'73731288'73760452'73765377'73795952'73804288'73819396'73841883'73845891'73863402'73865998'73884491'73933002'73951015'73964644'73971399'74013713'74042240'74079008'74081083'74128362'74159667'74167660'74168836'74192371'74268502'74281396'74287215'74291526'74309990'74313728'74316549'74352575'74385313'74400845'74404189'74409744'74414711'74417483'74417704'74422486'74428394'74431828'74432095'74432720'74494615'74499007'74546168'74557517'74576530'74579157'74587060'74593540'74600823'74637890'74643101'74667907'74676772'74680973'74699322'74705272'74706545'74732686'74763006'74763299'74764524'74765875'74767150'74769169'74773996'74782505'74788551'74789879'74791733'74791760'74803554'74815319'74819753'74833929'74834205'74837220'74868922'74873260'74875754'74876087'74881925'74895087'74897340'74901512'74901621'74902134'74912378'74929381'74964441'74969076'74971053'74975495'74982920'74990825'74996558'74999235'75007296'75013011'75020541'75040537'75045182'75046553'75050099'75052294'75054574'75062503'75064782'75064921'75065136'75066750'75068760'75068970'75069804'75074526'75075461'75080801'75086325'75086484'75087107'75087460'75090891'75096251'75096892'75099927'75106527'75120112'75124059'75126770'75132986'75134214'75139556'75153694'75155594'75156508'75166305'75172964'75173123'75175772'75176202'75178210'75179069'75179350'75179560'75191845'75199510'75200403'75203400'75205495'75210870'75218141'75221562'75224708'75225453'75228469'75232969'75237170'75238258'75244843'75245313'75245555'75248095'75249704'75250489'75252407'75252979'75254070'75265764'75267169'75270367'75270369'75273285'75273474'75273673'75284434'75285920'75297721'75306783'75308594'75309929'75318010'75321228'75332066'75333188'75338035'75349010'75359207'75362895'75371394'75378686'75385873'75397913'75399911'75414121'75417620'75422853'75425777'75431950'75433252'75437961'75438657'75445632'75449786'75463449'75465118'75472916'75473391'75487430'75487637'75489161'75489291'75490726'75491900'75492410'75500327'75508696'75511456'75512247'75513027'75516849'75523759'75529407'75539965'75540126'75542764'75543985'75547978'75550527'75551603'75553958'75557912'75560658'75566035'75567323'75569372'75571251'75572069'75573257'75574427'75575175'75577896'75579319'75581380'75582459'75582745'75583446'75588607'75597980'75598581'75604531'75606619'75607144'75607516'75612847'75612865'75615439'75617848'75623111'75624362'75626591'75627563'75637013'75638464'75639201'75640200'75643158'75643628'75644826'75645575'75648898'75650664'75651493'75651735'75651973'75652554'75654824'75656544'75658823'75659918'75664173'75665543'75665673'75666281'75666456'75668692'75670299'75670994'75671295'75672018'75673009'75680158'75682216'75682571'75684909'75685219'75685262'75685392'75688374'75688998'75690221'75690280'75690902'75690929'75694562'75695107'75696068'75699875'75701398'75701705'75703370'75703999'75704849'75712088'75713391'75721697'75724455'75726915'75727258'75744001'75753379'75756731'75759035'75759430'75761975'75762064'75764846'75764976'75766213'75769108'75771532'75775663'75776140'75783760'75785674'75787386'75795123'75798104'75799823'75810493'75811103'75814563'75818779'75822055'75822712'75825700'75826969'75849966%22%2C%22listid%22%3A%22p%5C%2Fall%5C%2F%22%2C%22description%22%3A%22All%20papers%22%2C%22urlbase%22%3A%22search%3Ft%3Dall%22%7D;

**Comment by kohler** [comment]
hotlist-info maintains the list state used to create the quick links (the links forward & backward in list order on paper pages).

**Comment by rfonseca** [comment]
Thanks!
