### ISSUE TITLE
HotCRP link is broken

### ISSUE THREAD

**Issue by stevenjswanson** [kohler/hotcrp#123]
The link in the lower right is broken

![pastedgraphic-2](https://user-images.githubusercontent.com/9068765/35073027-f514011a-fb9b-11e7-99fe-01d6c068913d.png)

Points to 

http://read.people.seas.harvard.edu/~kohler/hotcrp/

Which I doesn’t resolve (as of Jan 17, 2018).

**Comment by kohler** [comment]
This should be fixed (it actually points to read.seas.harvard.edu)
