### ISSUE TITLE
Downloading json with attachment downloads includes all papers

### ISSUE THREAD

**Issue by stevenjswanson** [kohler/hotcrp#126]
If I
1.  open a link to saved search: https://nvmw2018.hotcrp.com/search?q=ss%3Aprogram-data&qt=n&t=s&sort=

2.  Click 'select all 44 papers'

3.  Download JSON with attachments

I get a zip file that contains all the submissions to the conference, not just ones I selected.

**Comment by stevenjswanson** [comment]
Sorry, my mistake.  I was counting the final versions and the submitted versions.  How embarrassing. 

-steve

**Comment by kohler** [comment]
Np!
