### ISSUE TITLE
File attachment bug (supplementary material)

### ISSUE THREAD

**Issue by yallop** [kohler/hotcrp#128]
There appears to be something wrong with file attachment (supplementary material) submission.  I've recently had the following experience:

* submit a paper along with file attachments.  The submission was apparently successful (i.e. no errors were reported)
* check the page for the submission and notice that the supplementary material doesn't appear
* add the supplementary material again
* check the page for the submission and notice that the supplementary material now appears

Uploading has failed in this way more than once; I've previously submitted supplementary material along with a paper, and only discovered when the reviews came back that the upload failed.

**Comment by kohler** [comment]
Is this on hotcrp.com? If so you can email me which paper it is at which conference if you don’t feel comfortable posting it.

**Comment by yallop** [comment]
Yes -- I've sent more details by email.

**Comment by kohler** [comment]
Poster can no longer replicate.
