### ISSUE TITLE
PC chair cannot delete a test submission

### ISSUE THREAD

**Issue by nomeata** [kohler/hotcrp#132]
I am a PC chair, and made a test submission, under my name. I want to delete it, so I went to https://….hotcrp.com/paper/2/edit, pressed “Override conflict” and pressed “Delete”, but I only got this error message
> Only the program chairs can permanently delete papers. Authors can withdraw papers, which is effectively the same.

Maybe it is checking whether I am the author (which I am) and aborts before checking whether I am the PC chair (which I also am).

**Comment by nomeata** [comment]
I could delete it after editing it and changing the author name and e-mail address to “Someone else <someone@else.com>”. So it is work-aroundable.

**Comment by kohler** [comment]
Fixed in 74dc9021981a13343a40729c3e719eb64cf468be, thanks for the report.
