### ISSUE TITLE
Search leaks hidden tags

### ISSUE THREAD

**Issue by ben-stock** [kohler/hotcrp#135]
If you use the search to find a paper and start with a #, the auto-complete feature will leak which tags are around. This is not necessarily really bad (as you cannot actually see the papers tagged unless you have the permission to see the tag), but still inconsistent handling of "hidden tags".

**Comment by kohler** [comment]
Thanks for the report!

**Comment by ben-stock** [comment]
To add to that: if a reviewer has a hidden tag, you can still search for reviews from that person and will find them. Not too bad, but still a bit of an issue :)

**Comment by kohler** [comment]
You were expecting hidden tags to also be hidden when applied to PC members? I see why, but right now hidden tags only apply to *papers*.

**Comment by kohler** [comment]
(BTW, I believe the issue with hidden paper tags is fixed.)
