### ISSUE TITLE
Metareviews suggestions

### ISSUE THREAD

**Issue by ckaestne** [kohler/hotcrp#139]
Metareviews are a useful feature to summarize a discussion, but their current form have a number of quirks to work around.

Based on our experience this year, we would suggest a number of enhancements:
 * Reviewers assigned as metareviewers should have the same rights as reviewers who have already submitted primary reviews with regard to visibility. Specifically currently they cannot see author names if they are only revealed after the review.
 * Metareviews have all the fields of a normal review even though they are not needed. Expertise scores seem of little relevance and even the main score seems not needed. The distinction into summary and comments for authors is not really needed. (It would be possible to use public comments for the same purpose, maybe combined with discussion lead settings, but then it's not as easy to assign reviewers for metareviews through the same assignment process and not as easy to search for missing metareviews; I also like that voting works out of the box for metareviews as well)
 * It would be useful to show metareviews differently to the authors. We had to ask reviewers to include a title to mark their reviews as metareviews in their text.

**Comment by kohler** [comment]
Hi Christian,

I wish this were simpler. People use metareviews in different ways. In current HotCRP, differences in *review form* are expressed through the review round mechanism. Did you try that?

Eddie

**Comment by ckaestne** [comment]
Good point, I wasn't aware of this. With this we could likely address the second and their point easily. I'll try this next time :)
