### ISSUE TITLE
profile.php Internal Server Error master branch

### ISSUE THREAD

**Issue by cschmitt-mpi** [kohler/hotcrp#142]
Hi,

I recently set up a new hotcrp instance using a clone of the latest master branch.
Everything looks fine at the beginning, but if I create an initial account by using the webinterface the system tries to load profile.php which leads to a server error (see screenshot)

Apache error log 
[Thu Aug 02 16:11:35.537722 2018] [:error] [pid 3733] [client X.X.X.X:57529] PHP Fatal error:  Using $this when not in object context in <DOCUMENTROOT>/src/userstatus.php on line 682

Debian 8.11
PHP 5.6.33
mysql  Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3

Any idea how to fix that?

Thanks,
CArina

![screen shot 2018-08-02 at 16 10 50](https://user-images.githubusercontent.com/24299179/43589974-2d67f728-9670-11e8-9db7-23fb254593a6.png)

**Comment by kohler** [comment]
Whoops, sorry. Fixed in 29f9b77.

**Comment by kohler** [comment]
Should I close this issue @cschmitt-mpi ? Are you still seeing problems?

**Comment by cschmitt-mpi** [comment]
Hi,

Sorry, I did not find the time yet to check…but I’m using the tar release ;-)
But I’ll do and let you know.
CArina

> On 7. Aug 2018, at 19:05, Eddie Kohler <notifications@github.com> wrote:
> 
> Should I close this issue @cschmitt-mpi ? Are you still seeing problems?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—————————————
Carina Schmitt
Max Planck Institute for Informatics
Max Planck Institute for Softwaresystems
Saarland Informatics Campus
Joint Administration
IT MPI for Softwaresystems

Saarbrücken
Campus E1 5
66123 Saarbrücken
Phone: +49 681 9303 5814
Fax: +49 681 9303 6029

**Comment by cschmitt-mpi** [comment]
Hi Eddie,

I can confirm that everything’s working now.

Thanks for your fast help,
CArina

> On 7. Aug 2018, at 19:05, Eddie Kohler <notifications@github.com> wrote:
> 
> Should I close this issue @cschmitt-mpi ? Are you still seeing problems?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—————————————
Carina Schmitt
Max Planck Institute for Informatics
Max Planck Institute for Softwaresystems
Saarland Informatics Campus
Joint Administration
IT MPI for Softwaresystems

Saarbrücken
Campus E1 5
66123 Saarbrücken
Phone: +49 681 9303 5814
Fax: +49 681 9303 6029

**Comment by kohler** [comment]
Great, thanks.
