### ISSUE TITLE
Monitor external reviews: errorneous report of "All of your requested external reviewers have completed their reviews."

### ISSUE THREAD

**Issue by andreasabel** [kohler/hotcrp#143]
I am a PC member of POPL 2019 and have requested an external review via HotCRP, and the review has not been submitted (but I have submitted my own review). The page "Monitor external reviews" errorneously reports "All of your requested external reviewers have completed their reviews."
![screenshot from 2018-08-05 08-31-10](https://user-images.githubusercontent.com/1155218/43707095-75b50ad0-9967-11e8-828e-23e573e24469.png)

**Comment by kohler** [comment]
Thanks for the report, it should be fixed.

**Comment by andreasabel** [comment]
Thanks!
