### ISSUE TITLE
In the review edit mode, the scores of the other reviewers are blinded out

### ISSUE THREAD

**Issue by andreasabel** [kohler/hotcrp#145]
Even if I have submitted my original review already, the columns `OveMer` and `RevExp` only show my own scores when I am in the "Edit my review" (aka "Review") view. I only see them in the "Main" view.

(Not really a problem, but confused me, especially after my initial upload, where I thought for some reason I am not entitled to see the other scores.)

**Comment by kohler** [comment]
This is intentional, but I agree that it's a bit confusing. I'll try to figure out the best solution.
