### ISSUE TITLE
Feature request: download my review in "review-form" format

### ISSUE THREAD

**Issue by andreasabel** [kohler/hotcrp#147]
I'd like to be able to download my review in "review-form" format.
Scenario:
- I prepare my review offline in my favorite editor.
- I upload my review.
- I make some small changes online, e.g., to get correct errors in markdown and LaTeX formatting.
- I need to make big changes which I like to do in my favorite editor.

Thus, I'd like to
- download my review
- edit it
- upload it again

Currently, I can get my review in plain text, but then I will have to fiddle the content back into the review form manually.

For `emacs`, a workaround is:
- view the reviews and comments in plain text
- cut out my review and save it to "review-revised-online"
- do `ediff-buffers` on review(A) and review-revised-online(B) in emacs. Here, take the headers from A and the content from B.
- save the result as review-revised
- make the big changes
- upload

However, this is a bit fiddly and time consuming.

**Comment by kohler** [comment]
Andreas,

This is easy actually. You can download all reviews in editable format using Offline revieiwng (from home page). Or you can download a single review in editable format from the review page.
