### ISSUE TITLE
feature request: ability to group topics

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#153]
When submitting, it may be productive for authors to select topics from a list that organizes them in some helpful way, given that some conferences use dozens of topics. 

In ATC'18, the chairs achieved this goal by adding a common prefix to each topic group (see below). But this approach is somewhat cumbersome. It would be nice if HotCRP directly supports this by allowing administrators to explicitly group topics and assign a title to each group.

Thanks, Dan.

ATC'18 topics list:

Architecture:GPU
Architecture:Heterogenous hardware
Architecture:Miscellaneous / general
Architecture:Multicores
Aspect:Availability
Aspect:Consistency
Aspect:Economy
Aspect:Performance and efficiency
Aspect:Privacy
Aspect:Quality of Service (QOS, SLA/SLO, etc.)
Aspect:Reliability (replication, etc.)
Aspect:Scalability
Aspect:Security
Crosstopics: Approximate computing
Crosstopics: Caching
Crosstopics: Energy/power efficiency
Crosstopics: Graphs
Crosstopics: HPC
Crosstopics: Machine learning
Crosstopics: Migration
Crosstopics: Provenance
Crosstopics: Scheduling
Crosstopics: Transactions
DistributedSystems: Big data framework (Hadoop, Spark, etc.)
DistributedSystems: Consistency
DistributedSystems: Distributed file systems (HDFS, Ceph, etc.)
DistributedSystems: Internet of Things
DistributedSystems: Machine learning framework
DistributedSystems: Web browsing (page loading, etc.)
Network:Datacenter networking
Network:Protocols (TCP/IP, etc.)
Network:Software Defined Networking (NFV, etc.)
Network:Wireless/mobile networking
OS:Kernel
OS:Mobile computing (Android, etc.)
OS:Virtualization (VMs, Containers, etc.)
PL/SE:Compiler, translation, instrumentation
PL/SE:Data structure optimization (hashing, etc.)
PL/SE:Languages
PL/SE:Logging, monitoring, debugging, and troubleshooting
PL/SE:Parallelism
PL/SE:Program analysis and testing (static, dynamic, etc.)
PL/SE:Runtime management (GC, etc.)
Security:Attacks and bugs
Security:Attestation, transparency, and isolation (SGX Enclaves, etc.)
Security:Cryptography
Security:Encryption
Security:Miscellaneous / general
Security:Protocols (Blockchain, etc.)
Storage:Caching
Storage:Compression
Storage:Databases
Storage:Deduplication
Storage:Disk (CMR, SMR, etc.)
Storage:Distributed storage/file systems
Storage:Erasure Coding
Storage:Indexing / Searching
Storage:Key-value storage
Storage:Local file systems
Storage:Non-Volatile Memory
Storage:Remote memory (DSM, RDMA, etc.)
Storage:SSD / Flash

**Comment by kohler** [comment]
Having so many topics is a mistake—it seems pretty clear that such granular information helps neither submitters nor PC members.

Nevertheless, grouping isn't a bad idea and I implemented a version of it. If you enter topics named like that, they will be displayed like this to editing users:

![image](https://user-images.githubusercontent.com/410647/50456904-ba90c300-0925-11e9-816c-2aa0b94a7b3a.png)

There are some smaller changes on the search side.

But topics will continue to be specified as textual strings and the admin UI will not be changed, that seems pointless to me.

**Comment by kohler** [comment]
(As always of course patches welcome and feel free to expand what you meant.)

**Comment by dants** [comment]
Thanks for adding the feature! It looks very nice. (I assume this topics presentation happens if one uses a colon in the names of topics, like so: "subtitle:topic"? If so, a sentence explaining this would be helpful in 'Settings' / 'Submission form', under 'Topics'.)

I'm hesitant to use the feature, because we've opened the hotcrp site before it was added, and the authors + committee members already used the existing topics. If one updates the name of an existing topic, does the association between that topic and the submissions + committee members who used it remain, despite the change?

**Comment by kohler** [comment]
Yes, if one updates the name of an existing topic, the association remains despite the name change.

**Comment by dants** [comment]
A third comment: 

When displaying the topics, e.g., in https://[conf].hotcrp.com/search?q=show%3Atopics+&t=all, topics are shown with their group prefix, which makes them far less readable, with multiple repetitions of potentially long strings. For example

> _"[...] technique/aspect:experimental methodology; technique/aspect:performance, efficiency; technique/aspect:scheduling, resource management"_

Therefore, personally, I would've much preferred it if the prefixes weren't shown---at least if their removal doesn't create ambiguity between topic strings. Same goes for search, I guess. In my mind, topic groups are simply a way to organize the submission form; nothing else.

Thanks,
--Dan

**Comment by dants** [comment]
Comment #4:

It seems the new feature of grouping topics wasn't applied to https://conf-name.hotcrp.com/profile (PC members must insert their topics of interest as well). Could you please apply the fix to the 'profile' too?

Thanks,
--Dan

**Comment by kohler** [comment]
Re No. 3, I agree that “Technique/Aspect” is verbose, but we disagree on whose fault that is.

**Comment by dants** [comment]
> _"[...] net:network protocols; net:SDN, NFV; net:wireless"_

is also cumbersome and overly verbose relative to the much cleaner:

> _"[...] network protocols; SDN, NFV; wireless"_

even though the title is composed of only three characters. Which is why I'm going to soon delete all titles from topic names, if the implementation remains as is. My original feature request was a way to help organize the submission form, but it's not worth it if it makes topics cumbersome.

We agree that the verbosity is my fault, and that it's unhelpful to users because the title is made part of the topics. This is why I proposed not to make titles part of topics -- verbosity can be helpful to users in that case.

**Comment by kohler** [comment]
I may make further changes.

And you should definitely keep the topic grouping until at least the submission period has passed. You are being way too dramatic about “cumbersomeness” and “oververbosity” and random alternatives you came up with being “much cleaner.” The problem is you have 62 topics, that is inherently cumbersome and verbose.

Your current concern should be the submission form. I encourage you to use initial capital letters (which will help them stand out in lists) and fuller English words in their names (rather than “net:SDN”, say “Networking: SDB, NFV”). And next time use fewer topics.

I also want to point out that this kind of work is not part of my contract with USENIX. You are getting free open-source work here.

**Comment by dants** [comment]
I understand it's free open-source support and, as always, very much appreciate it!

It wasn't my intention to be dramatic. I explained that what you implemented is -- for us -- not preferable over the alternative (as I think that _"network protocols; SDN, NFV; wireless"_ is much clearer than _"Networking:network protocols; Networking:SDN, NFV; Networking:wireless"_). I hope that that's okay. 

I don't believe I proposed any "alternatives"; we requested one very specific feature, which is a way to organize topics in the hotcrp forms, without having to change the topics. (This was just a request, and I understand that it is the nature of open source that many requests aren't granted.)

Like you, we didn't particularly like the idea of using ~60 topics. We seriously considered consolidating most of them. But we looked at the data from ASPLOS'19 and ATC'18 and learned that reviewers and authors do use most of them. And considering the task of bidding is really hard when there are hundreds of submissions, and since PC members do primarily rely on topics when bidding as a way to cope with the submissions volume, we eventually decided it might be counterproductive to mess with the topics and risk making bidding even harder. While it is possible less topics are preferable, we can't know for sure, and we decided to be conservative.

We've already decided not to revert the topics back until after the deadline, like you suggested. After, topics will work better for us without the prefix.

Thanks again,
--Dan

**Comment by kohler** [comment]
I’ve made some further changes on topic display, including spacing, changes in topic interest entry, etc., and may tweak further. Further feature requests should be entered elsewhere.

For the sake of documentation, here are the problems I had with implementing topic grouping “without changing the topics”:

1. If topic groups are useful for entry, then they are useful in other contexts.
2. If topic groups are metadata (i.e., not part of the topic), then it would be awkward or impossible to enter topics such as “Networking: Other” and “Storage: Other” (because the “Other” part would not be unique).
3. If topic groups are metadata, then the order in which topics are presented would either change from context to context (e.g., alphabetical including group on edit pages, alphabetical not including group elsewhere) or be confusing.
4. Users would expect to be able to search for “topic:networking” to get all “networking” topics.
5. Most papers have relatively few topics so the display problem seems independent of the way groups are displayed.
