### ISSUE TITLE
feature request: live-meeting-tracker for dual-track meetings

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#154]
Due to the increasing number of submissions to system conferences, several recent program chairs resorted to splitting the meeting into two parallel tracks (each simultaneously headed by a different co-chair), at least part of the day, to be able to finish meetings on time.

This has been the case for ATC'18, ASPLOS'18, and ASPLOS'19, and will be the case for ATC'19. Assuming that the number of submissions isn't going down, it seems dual-track meetings are here to stay.

A main problem in holding dual-track meetings is that the HotCRP live-meeting-tracker feature becomes unusable, making the task of running the meeting more challenging. If possible, any solution that addresses this issue -- by allowing to track two meeting tracks simultaneously -- would be very much appreciated.

Thanks, Dan

**Comment by kohler** [comment]
This feature is now supported.

**Comment by dants** [comment]
Great, thanks! Much appreciated!
