### ISSUE TITLE
failing to use add_tags / remove_tags

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#157]
When doing bulk updates through https://---conf---.hotcrp.com/profile/new#bulk, it seems like hotcrp ignores remove_tags and add_tags. For example, if a PC member somebody@here.com is tagged with "test", then bulk-updating by uploading this csv file:

    email,remove_tags
    somebody@here.com,test

seems to have no effect: the "test" tag remains associated with somebody@here.com despite its removal. Same goes for add_tags. Am I missing something?

**Comment by kohler** [comment]
Thanks for the report!
