### ISSUE TITLE
limit increase request: ability to download entire action log

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#158]
Once, hotcrp instances allowed their admin to 'show' the entire 'action log' by increasing the 'show records at a time' value to be big enough at https://conf-name.hotcrp.com/log. This ability allowed the admin to conveniently copy-paste the entire log, save it as text, parse the resulting file with some script, and generate useful graphs such as this one:

http://www.cs.technion.ac.il/~dan/files/submissions.jpg

It seems like, currently, hotcrp limits the 'show records at a time' value to be at most 200, which means it is no longer possible to conveniently accomplish the above. Would you be willing to please consider restoring/adding the ability to download the entire log in one go?

Thanks,
--Dan

**Comment by kohler** [comment]
the max count was instituted in 2014
