### ISSUE TITLE
pdf format checker problem

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#159]
It seems like there's a problem with hotcrp's format checker, best explained through an example:

With Usenix format rules, the 'line height' in https://conf-name.hotcrp.com/settings/subform should be set to 12pt. Surprisingly, when checking, I've learned that the Usenix tex template fails the 12pt-line-height check when pdflatex-ed. After tweaking the template for a while (see https://www.usenix.org/sites/default/files/usenix2019_v3.1.tex) , with much trial and error, I was finally able to arrange things such that, when pdflatex-ing it, the resulting pdf would cleanly pass the hotcrp pdf format checker (see https://www.usenix.org/sites/default/files/usenix2019_v3.1.pdf).

Such tweaking isn't something you'd want to subject regular authors to (to say the least), because even minor, meaningless, perfectly legal regular text edits applied to the tex cause the resulting pdf to fail the hotcrp format check, with the following error message: http://www.cs.technion.ac.il/~dan/files/hotcrp-fmt-err.png

> _"Line height too small: minimum 12pt, saw values as 11.9pt (pages 1-2)"_

For example, if you delete everything but the first sentence in the the caption of Figure 1 in https://www.usenix.org/sites/default/files/usenix2019_v3.1.tex, then pdflatex, and then check the format of the resulting pdf, hotcrp will produce the aforementioned error message. And while I'm sure the checker is right, it doesn't change the fact we don't want to make all users suffer through the process of figuring out why and coming up with some (arbitrary) way to fix it through text modifications.

To shield users from this, our workaround was to configure hotcrp to use a 'line height' of 11.9pt. Realizing that that's the "right" thing to do took me a good few hours. And so, if possible, I think future chairs will very much appreciate it if the problem is resolved internally within hotcrp, perhaps by configuring the checker to tolerate violations of less that 1% (> 11.9pt /12pt) without complaining?

Thanks,
--Dan

**Comment by kohler** [comment]
upload a problem pdf

**Comment by dants** [comment]
See https://atc19.usenix.hotcrp.com/doc/atc19-paper95.pdf

If you change 'line height' from 11.9pt to 12pt,  the format checker will generate the error for this file. The only difference -- in tex files -- between the above and 

https://www.usenix.org/sites/default/files/usenix2019_v3.1.pdf

is the caption of Figure 1 (which is a bit longer in the latter).

**Comment by odeinjul** [comment]
Still meet this problem, solved by setting ```\baselineskip=12.1pt``` at the error occurring section.

**Comment by kohler** [comment]
1. Please do not comment on random closed issues
2. Comments without mechanisms that would allow replication, e.g. a problematic PDF, are unhelpful
