### ISSUE TITLE
personal/hidden tags shown globally to admin

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#161]
(This may be related to https://github.com/kohler/hotcrp/issues/135 )

As admin, when searching with tags, I see personal tilde-prefixed tags added by non-admin PC members. This isn't a big deal, but it (1) clutters the list of tags that pops up while I type, populating it with tags that are irrelevant to me, and it (2) leaks information that may be perceived as private, even without me explicitly switching to these members' view.

**Comment by kohler** [comment]
I can’t replicate this.

**Comment by kohler** [comment]
The likelihood that actually happened that way is, like, zero.

**Comment by dants** [comment]
I'm able to reproduce it now.

**Comment by dants** [comment]
Re-doing these steps again, I can't reproduce. You're right. Apologies.
