### ISSUE TITLE
Feature Request: Schema only install

### ISSUE THREAD

**Issue by ErroneousBosch** [kohler/hotcrp#164]
Requiring MySQL root access and universal grant privileges is overkill, insecure, and impractical in a shared DB environment. 

Can a flag be added to the createdb.sh script that would allow bypassing this and simply create the schema schema in-situ in a previously created database?

**Comment by kohler** [comment]
No, but I have now explained in README.md what is required. If you want to add a flag to createdb.sh I will consider the pull request.
