### ISSUE TITLE
Textual export does not honor draft status of response

### ISSUE THREAD

**Issue by ben-stock** [kohler/hotcrp#169]
I recently noticed that the draft of the authors' response is previewed in the "recent activity", although it is not yet submitted. Looking at the paper itself then hides the response, but when exported as TXT, the entire response draft is visible.

Not a totally problematic thing, but likely not intended :)

**Comment by kohler** [comment]
Thanks for reporting this. I believe it's fixed in ec2c1c66a5a8e771f2488546413cd09746da5d7e. Please reopen if it's not.
