### ISSUE TITLE
default bid values

### ISSUE THREAD

**Issue by JuliaLawall** [kohler/hotcrp#176]
Currently the preference boxes contain a grey 0 before one enters some information.  From having done a paper assignment, it seems that if the PC member does not put a preference value, the value is not 0, but is rather the topic score.  To avoid misunderstanding, it could be better to make the grey value the actual topic score, rather than 0.

**Comment by kohler** [comment]
This isn't correct. Preference outranks topic score: if papers have different preferences, the preference value wins. In a future update, the topic score will be used only to differentiate among papers with 0 preferences—i.e. papers with the same non-zero preference will be assigned with equal weight.

**Comment by JuliaLawall** [comment]
On Mon, 20 May 2019, Eddie Kohler wrote:

>
> This isn't correct. Preference outranks topic score: if papers have
> different preferences, the preference value wins. In a future update, the
> topic score will be used only to differentiate among papers with 0
> preferences—i.e. papers with the same non-zero preference will be assigned
> with equal weight.

OK, I see.  The explanation says "using topic scores to break the ties".
So a paper with a topic score of 20 and nothing in the preference box will
disfavored as compared to a paper with 1 in the preference box?  That
seems fine, so no issue.

thanks,
julia
