### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by JuliaLawall** [kohler/hotcrp#185]
I spend a lot of time telling people to edit their reviews, because the markdown interpretation renders:

P1: first point
P2: second point

as

P1:first point P2:second point

which is not very readable.  Would it be possible to be more selective about when the text is interpreted as markdown?  Another common problem is indenting sub-points, which then come out as tt font.

**Comment by kohler** [comment]
I don't think this feature is well-defined or would be worth the time it would take.

Just curious, did you ask people to make their points in that way? The idiomatic Markdown way to do this would look like

```
* P1: first point
* P2: second point
    * P2.1: second subpoint
```

which renders like

* P1: first point
* P2: second point
    * P2.1: second subpoint

**Comment by JuliaLawall** [comment]
I'm not sure that everyone realizes that they must write markdown.

**Comment by kohler** [comment]
Both the Web site and the downloaded review form say “Markdown styling and LaTeX math supported” over every text field.

**Comment by JuliaLawall** [comment]
Supported doesn't mean enforced.  I always assumed that the message meant that if one used markdown annotations, then things would be interpreted as markdown.  And if one didn't use markdown, then nothing would happen, and the text would appear exactly as it was typed.  "Comments must be written using markdown" or "The comment section is interpreted as a markdown document" would be much clearer.  But it could still be useful to have a checkbox to allow people to disable markdown entirely, if they didn't write their review with markdown in mind.

**Comment by kohler** [comment]
“Styling with Markdown is supported” is what this box (GitHub comment) says, for example, although it also has mandatory Markdown. “If one didn't use markdown, then…the text would appear exactly as it was typed” would be extremely brittle, as well as annoying to implement: even one use of `*emphasis*` or one LaTeX formula might radically change the appearance of a review. So that was an incorrect assumption you had. But thank you for further explaining your position, I will try to update the text. I strongly believe a checkbox would be more trouble than it is worth.

**Comment by JuliaLawall** [comment]
On Sun, 28 Jun 2020, Eddie Kohler wrote:

>
> “Styling with Markdown is supported” is what this box (GitHub comment) says,
> for example, although it also has mandatory Markdown. “If one didn't use
> markdown, then…the text would appear exactly as it was typed” would be
> extremely brittle, as well as annoying to implement: even one use of
> *emphasis* or one LaTeX formula might radically change the appearance of a
> review. So that was an incorrect assumption you had.

I think your position is one of someone who knows markdown and my position
is of one who doesn't.  The goal of markdown seems to be very unobtrusive,
eg if it was latex, one would be informed immediately if one were not
using it properly.  Furthermore, one never looks at ones own reviews.  So
years and hundreds of reviews can go by with one never realizing that
there is an issue.

I often write reviews that contain lines like

this is a badly written sentence ->
this is a better written sentence
"better" is more positive than "badly"

I now realize that these are all coming out badly formatted because all of
the newlines have been removed.  No problem for the one after the arrow,
but the change and the explanation are running together.

Looking on the internet, it seems that one can end a line with two spaces
to preserve a newline, but there is some discussion about it, which
suggests that it is not well known.  Having the newlines preserved would
be of much higher value to me than eg having boldface section titles,
which is decorative but not really useful.

julia
