### ISSUE TITLE
ACM tag order not reflected in generated TOC XML 

### ISSUE THREAD

**Issue by rfonseca** [kohler/hotcrp#187]
Steps to see problem:
1. Created a tag (acm:pub) and listed the tag as the 'Publication Tag'
2. Before ordering the tag, generated an XML TOC file for ACM. The papers were ordered in numeric paper order.
3. Created an order for the tag, according to the paper order in the conference.
4. Generated the XML toc again, but the order in the XML file remained in numeric paper order, and not according to the tag.

Is there a fix for this? Is the fact that we first generated the TOC without the ordering the cause?

**Comment by kohler** [comment]
Hi Rodrigo!

I don't believe that the order of papers *in the TOC* is relevant. The order in the *bundle* is relevant, and in that download, the order is respected. But ACM changes things all the time. Let me know if you think the order is relevant.

**Comment by rfonseca** [comment]
Thank you Eddie, that is good to know. It's my first time dealing with the DL stuff. The order is correctly reflected in the bundle, so things should be fine.
