### ISSUE TITLE
Rebuttal word limit indicator too early on portrait-mode phone

### ISSUE THREAD

**Issue by dbittman** [kohler/hotcrp#188]
When I review a submitted rebuttal on my phone (Android 10, chrome browser) in portrait mode, the rendered word limit (red background) indicator appears too early (in the one I viewed, it showed the limit to be at ~20% too early). When viewed on the same device in landscape mode, it rendered at the correct location, as it did on a non-mobile device and on an ipad. I haven't checked iphone since I don't have one.

Probably a minor issue, since I doubt reviewers are reading rebuttals on their phones, but if they do they might stop reading early! I can provide screenshots, but haven't done so to protect anonymity / double-blind.

**Comment by kohler** [comment]
Thanks for reporting this, in d8055ea6248aa3cd3d7e758c8c0306c176c5ad10 it is fixed.

**Comment by hkerma** [comment]
Hello, I have noticed the same issue in a recent conference (cycle2.sp2025.ieee-security.org).
Is there any way to know if the conference is using an outdated hotcrp version? Or does the issue still exist?

**Comment by kohler** [comment]
IEEE security has chosen to run an outdated version of HotCRP that they “support” themselves—or not. Problems with IEEE Security instances should not be reported here.

**Comment by hkerma** [comment]
Thanks for the prompt reply; I just wanted to make sure.
