### ISSUE TITLE
Impossible to remove "No entry" options

### ISSUE THREAD

**Issue by nc2y** [kohler/hotcrp#191]
It does not seem possible to change a review field from optional to mandatory in the current version (v2.102 [d2a26...]). 
To reproduce: 

1. Create a review field, say "Overall zaniness"
2. Add a "No entry" option to the list of scores, save changes
3. Delete the "No entry" option, and save changes again

Result: HotCRP informs me there are no changes, and the "No entry" option is still there.  If I cosmetically tweak one of the other entries to force it to consider the change, the "No entry" option remains.

I can delete "Overall zaniness". If I try to bring it back, the "No entry" option is back, even if I try to remove it.

**Comment by kohler** [comment]
Thanks for the report!
