### ISSUE TITLE
Permission error when clicking "Your submissions" link as an author

### ISSUE THREAD

**Issue by SimonJF** [kohler/hotcrp#192]
Hi,

Thanks for your work on HotCRP.

Clicking the "Your submissions" link:

![image](https://user-images.githubusercontent.com/4552508/73362773-5d411100-429f-11ea-8a38-5b49a3b0b238.png)

as an author before reviews are available seems to try and show the "OveMer" column. This data (correctly) isn't accessible as an author, so HotCRP shows a permission error:

![image](https://user-images.githubusercontent.com/4552508/73362593-03404b80-429f-11ea-8152-f077605261f6.png)

This happened on hotcrp.com (I can share specifics in private if needed).

**Comment by kohler** [comment]
Hi Simon, sorry for not getting back to you earlier. I fixed this issue in 0a14cc5d5b7dd8e4b6283dd22a4f5532114b2cce.
