### ISSUE TITLE
External review request note -- missing?

### ISSUE THREAD

**Issue by cca88** [kohler/hotcrp#196]
When a PC member does "Propose an external review" , then the input form asks for an "Note to reviewer (optional)".   With approval of external reviews set to on, this note is shown to the Admin in 
the email sent for approving the external review request. (introduced by "They supplied this note: ").

However when the external review request is sent after approval, the note is not included, which may lead to confusion.

Either (1) there is a hidden setting that lets this note disappear, and the docs should mention this better; or (2) the designation "Note to reviewer" is misleading, because it is a note to the admin; or (3) the note should really be included in the email.

In this case, I am referring to the HotCrp.com install of a conference running now. The template
for external review requests was not edited, and it contains:

``
%IF(REASON)%

They supplied this note: %REASON%%ENDIF%
``
which should include the note (=REASON).

**Comment by kohler** [comment]
Should be fixed, thanks for the report!
