### ISSUE TITLE
required fields in submission, but only on final version

### ISSUE THREAD

**Issue by kmccurley** [kohler/hotcrp#197]
We would like to have a field on the submission form be required, but only for final versions. There are several obvious use cases for this:
1. identify the speaker
2. submit a copyright form
3. upload slides

Is it even possible to do this? I tried setting something as required and only shown on final papers, but it showed up as required without having input even showing on the form. Are these attributes of "final" and "required" mutually exclusive?

**Comment by kohler** [comment]
If this was a hotcrp.com site I think it's fixed. Please take a look & let me know. Thanks!

**Comment by kmccurley** [comment]
This was not on hotcrp.com - it was on a branch of your open source version. We merged your most recent changes into our branch, but this appears to still be a problem. Then I installed from your repository and saw the same thing.

To restate the problem clearly:
* we have a field that is required but only shown on a final submission. In the "options" row of Settings, the field shows up as: ```{"id":7,"name":"Field test","type":"checkbox","position":5,"description":"This is only on final submissions.","final":true,"display":"prominent","required":true}```
* We have unchecked "Collect final versions of accepted submissions" under settings, so the option does not show up on the submission form.
* When the author submits a paper, it shows the warning below:
![image](https://user-images.githubusercontent.com/14105363/76791171-83524000-677d-11ea-9b1f-c8e456baf089.png) This is very confusing because there is no field by that name, so the author would be unclear on what they have to do. The URL after they submit is ```paper/1/edit?post=p21tk18rjh07```

I believe that the problem is in src/paperstatus.php on line 308:
```
301         foreach ($this->conf->paper_opts->option_list() as $o) {
 302             if ($user && !$user->can_view_option($prow, $o)) {
 303                 continue;
 304             }
 305             $ov = $prow->force_option($o);
 306             if ($o->test_required($prow)
 307                 && !$o->value_present($ov)) {
 308                 $this->error_at_option($o, "Entry required.");
 309             }
 310             $oj = $o->unparse_json($ov, $this, $user);
 311             if ($oj !== null) {
 312                 $options[$this->export_ids ? $o->id : $o->json_key()] = $oj;
 313             }
 314         }
```
I am guessing that the $user->can_view_option($prow, $o) is returning true, but honestly I cannot understand that code.

**Comment by kohler** [comment]
Does 3ee731112465c0de258daf47e6b0cafcd6753688 help at all?

**Comment by kmccurley** [comment]
I pulled in that change, but it didn't seem to help at all.

**Comment by kohler** [comment]
I did check the above commit (685d431) in combination with 3ee7311

**Comment by kohler** [comment]
Reopening until you confirm the fix…

**Comment by kmccurley** [comment]
That last fix appears to have solved the problem. I believe you can close the issue now.
