### ISSUE TITLE
Generated email may fail to comply with RFC 2822

### ISSUE THREAD

**Issue by kmccurley** [kohler/hotcrp#198]
We've been seeing emails get rejected when sent to program committee members. It took me a while to track down what the error is, but I finally found the smoking gun. The particular email being rejected was a review with a line of 1210 characters in PaperReview::tfields (I have omitted the actual review from this issue since they should remain confidential). The exim4 log shows a line of:
```2020-03-18 10:29:00 1jEVwa-0003LT-5m ** mohammad@virginia.edu R=smarthost T=remote_smtp_smarthost: message is too big (transport limit = 1)```

I checked with our upstream smtp smarthost and they report that max message size is not the problem with them.  After searching on the web, it appears this is caused when a message is sent out that has a single line longer than 998 characters (see [RFC 2822](https://tools.ietf.org/html/rfc2822#section-2.1.1)). I've read up and apparently there is a [configuration change on our mail server](https://stackoverflow.com/questions/54972465/exim-v4-91-cant-enable-ignore-smtp-line-length-limit-1-macro-to-allow-long-li) to set IGNORE_SMTP_LINE_LENGTH_LIMIT=1. We made this change, but I think the receiving server will still be within their rights to reject the message because it violates the RFC.

This raises the issue of how to properly fix the problem. In my opinion hotcrp should do one of the following:
* (option 1) on the server side, reject submission of a review with a line longer than 998 characters. Perhaps there are other checks made on the submission to include required fields.
* (option 2) impose a regex form validation constraint on the <textarea> fields in the review form (with names=t01, t02, t03). This could be accomplished with a pattern constraint in HTML5. This is supported by all major browsers, but I don't know what the regex would look like.
* (option 3) use javascript triggered on form submission to validate the contents of the textareas.
* (option 4) have the mail program apply line-wrapping. This runs the risk of corrupting the contents of the review, but it seems like a safer solution since there are many other kinds of emails sent out by hotcrp.

**Comment by kohler** [comment]
Thanks for this report. I'm fixing it using quoted-printable content-transfer-encoding, which I think is a reasonable fix.
