### ISSUE TITLE
PC chair view on mail log

### ISSUE THREAD

**Issue by kmccurley** [kohler/hotcrp#202]
It appears the action log does not include entries from the MailLog table. These would be nice to see.

**Comment by kohler** [comment]
FYI, the action log *links* to entries from the MailLog table. Example

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/410647/91333647-d81dcc00-e79b-11ea-952d-1522f4d17d45.png">

The “mail #13” link will show the relevant MailLog entry.
