### ISSUE TITLE
90941b1b485e6b57cfe99ddd39232d4233bf35d4 broke signin

### ISSUE THREAD

**Issue by asl** [kohler/hotcrp#203]
Hello!

We are running HotCRP instance on hotcrp.llvm.org for LLVM devellopers' meeting. After updating to 90941b1b485e6b57cfe99ddd39232d4233bf35d4 the signin / signout links do not work anymore, I'm just receiving 404 when clicking "Sign in" button. The request goes to ```https://hotcrp.llvm.org/usllvm2020/signin``` and not handled.

Please advice. No local changes, etc.

PS: Reverting back to 8464d51 fixes the problem, and we currently rolled back to this revision.

**Comment by kohler** [comment]
Did you really go to 90941b1? We are now much later. HotCRP.com, fwiw, is on 6349e31d84924a2a5bd809abf7c62f65efaed462. There have been some bugs in login.

**Comment by asl** [comment]
Oh, sorry for being not clear. The problem was seen on HEAD. I bisected it down to 90941b1..

**Comment by kohler** [comment]
OK, then I need more. Are you using LDAP or some other kind of login other than HotCRP? Are you using Apache or Nginx or …?

**Comment by asl** [comment]
No LDAP, just plain MySQL w/o anything special. Apache.

**Comment by kohler** [comment]
I think I know what is going on. I have not tested on Apache for years, and new HotCRP, unlike old HotCRP, effectively requires that all Web requests be routed to `index.php`, which then delegates elsewhere. Your Apache setup is probably looking for `signin.php`, which does not exist.

**Comment by kohler** [comment]
I think e2667ae74 may fix this.

**Comment by asl** [comment]
Yes, I thought something like this, but checked rewrite patterns instead :)

Fix confirmed, thanks!

**Comment by kohler** [comment]
Great, sorry you encountered a bug!
