### ISSUE TITLE
Accepted review request from wrong account

### ISSUE THREAD

**Issue by mhandley** [kohler/hotcrp#208]
Hi Eddie,

I was assigned an external review request, but accidentally accepted the request from the wrong hotcrp.com account (I didn't intend to have two accounts, but I can never remember which email address I used for what).  HotCRP did not show an error when I accepted the review request from the wrong account, but then (correctly) does not let me review the paper using that account.  I can review it from the correct account, so no problem there.  

However, using the wrong account (which I do have a paper submitted under) when I display all the papers I'm allowed to see, I get permission errors displayed, so it looks like HotCRP did store some information when I accepted the request.  This isn't a problem for me at the moment, but as it's unexpected behaviour and might potentially have corrrupted some state, I thought it worth reporting.

Mark
![hotcrp](https://user-images.githubusercontent.com/29434236/89031549-9b8cbb00-d32a-11ea-9f75-fcba72f0835f.png)

**Comment by kohler** [comment]
Dear Mark,

It is delightful to hear from you; should I start enforcing Mark Handley-specific bugs just to hear from you more often???

There is some weird state hanging around, but not damaging or unsafe state, and it is only stored in your session. Nevertheless these errors shouldn't be displayed & I will work to remove them!

Eddie

**Comment by mhandley** [comment]
Hi Eddie, there are probably easier ways to hear from me!  Hope you're keeping well this very strange year.

Anyway, thanks for checking - didn't seem like a big deal, but I appreciate how the causes of bad state can sometimes be hard to track down, so thought it worth mentioning.  

Mark
