### ISSUE TITLE
PDF checker font size

### ISSUE THREAD

**Issue by signorello** [kohler/hotcrp#209]
I am having two issues with the PDF checker verifying the font size in the submissions. Namely,

(i) a paper with a bigger font size does not raise any error (10pt set as parameter for the checker, 11pt used in the attached tested pdf);
[Master__Template_wrong_BiggerFont.pdf](https://github.com/kohler/hotcrp/files/5116778/Master__Template_wrong_BiggerFont.pdf)

(ii) references too are checked by the checker, inevitably raising a "too small font error" like the following:
"Body font too small: minimum 10pt, saw values as small as 8pt (page 5)"
[Master__Template_correct.pdf](https://github.com/kohler/hotcrp/files/5116782/Master__Template_correct.pdf)

For the above, I have been using the following class of the ACM official templates:
% Proceedings format for SIGPLAN conferences 
\documentclass[sigplan, anonymous, authordraft, review=false, 10pt]{acmart}

I would like to ask whether or not the behavior in (i) is the intended one, and if there might be a way to avoid the error message in (ii).

Thank you for help

**Comment by david-waterworth** [comment]
I'm observing this as well - we're trying to submit to an ACM conference using `\documentclass[sigconf]{acmart}`. The body font is 9pt and the references are 7pt I believe. I'm seeing

> Body font too small: minimum 9pt, saw values as small as 7pt (page 4).
> Line height too small: minimum 10.5pt, saw values as small as 8pt (page 4)

Removing the references "fixes" the issue. So the conclusion I've come to is that the PDF checker is in fact treating the references section as body test. Confirmation would be good though as we're trying to submit the camera ready version.

**Comment by kohler** [comment]
It is difficult to reliably distinguish sections of a document that are references from sections that contain body text. The format checker can make mistakes. However, in 2a2238692f547d7bb5e1aa98ec207071b86be785 and 80959c17370d9bf4059ded8ae477cec3945e6f5f, I have tried to make it smarter, and it will now attempt to distinguish sections of a page that contain references from those that contain body text. The ACM template no longer reports a problem..

To the first question above, by default the format checker only checks a *minimum* font size, but if you give a range of sizes  as in “10-12pt” or “10±0.2pt” it will check for a maximum too.
