### ISSUE TITLE
use for journal

### ISSUE THREAD

**Issue by ivotron** [kohler/hotcrp#211]
Hi, we are evaluating hotcrp for JSys, [a new diamond open-access journal for systems research](https://medium.com/@vijayc/a-new-journal-for-systems-research-2dbbfca6b860). Is there a "journal mode" with editorial management features like managing a pool of reviewers for each volume/issue? thanks!

**Comment by kohler** [comment]
Hi @ivotron, there isn’t an explicit mode, no. The thing that I think would work worst is managing submission deadlines. For reviewer pools, one could use tracks and PC tags to get some of the desired effect. SIGCOMM CCR, which has a more journal-like workflow, does use HotCRP. You could check with Hamed Haddidi how that's going.

**Comment by kmccurley** [comment]
I had a couple of comments about this. First, the CS community has started to use hybrid "journferences" in which there are periodic deadlines, and these are grouped together as papers for a conference. This is different from a traditional journal in which there is no such thing as a "submission deadline". The reviews for a paper can be submitted at any time, and only when a final decision is made does the activity for that paper come to an end. In a "journference" model, there are deadlines for reviews and papers that are not accepted for a given deadline might roll forward to the next deadline. In this case it would be good to carry forward the papers that were not accepted for a given deadline, along with the accounts of authors and reviewers.

It's worth noting that there are two modes for using HotCRP: the hosted version on hotcrp.com and the open source version. It looks like SIGCOMM CCR uses the hosted version, which I believe has a shared authentication mechanism for all HotCRP instances there (Eddie should correct me if I'm wrong). This might at least make it more convenient for carrying accounts forward. We use the open source version of HotCRP for Transactions on Symmetric Cryptology, which is a journal that is linked to the FSE conference, and has "rolling deadlines". In our case there is a deadline for a volume every three months, and we have to set up a new instance of HotCRP for each volume. This is a little unfortunate, but it's the only solution we have come up with. If a paper is not accepted for one volume, the author is free to revise it and submit to the next journal volume, but then we are not able to carry forward the reviews from the previous volume. 

In the future I think it would be helpful to have HotCRP support such venues, but I'm not sure how much work it would require. Eddie is best able to field that question. Perhaps it could be enabled by an import feature to a new HotCRP instance, importing data from a previous instance (papers that had no decision, and accounts for PC members and authors).

**Comment by ivotron** [comment]
thanks for the reply @kohler! I think that answers our question. And thanks a lot for sharing your experience @kmccurley, that's really insightful.

**Comment by kmccurley** [comment]
This was closed long ago, but I was wondering if the new feature of "Submission classes" might make HotCRP more useful for journals. A submission class could theoretically have different submission deadlines, so I wonder if it's possible to create an instance and then add a submission class with a different deadline for each issue. After the deadline for a given issue, decisions could be made about the papers submitted for that issue. Then when the next issue deadline passed, you could make decisions for that submission class. You probably wouldn't do this in perpetuity, but it could at least be useful for a year while the set of reviewers remains fairly steady. Is there any flaw in my reasoning here?
