### ISSUE TITLE
Installation Instructions - Addtional Information

### ISSUE THREAD

**Issue by kdhallbgm** [kohler/hotcrp#214]
Hello,

I'm trying to set up a quick HotCRP installation for internal purposes.  Since I don't work much with Nginx I was looking for a bit more information about the file tree layout and typical Nginx/FPM configs for a working HotCRP installation.  The README.md file gives fragments that I could probably understand better after learning Nginx, but it seems that it would be handy to include a working sample configuration (somewhere else in the Git tree if it's too big for the Readme).  

Also, is there a script or URL for verifying a new installation?  I see the 'test' directory, but I don't see how to use it.

If this information is actually already there somewhere, please send me a link as I haven't been able to find it yet.

Thanks.

-Dave

**Comment by Bramas** [comment]
Hi,
If you want, you can use docker compose using the config I created to easily deploy HotCRP:

https://github.com/Bramas/hotcrp-docker-compose

I successfully used it in production for a conference and it worked really well.
