### ISSUE TITLE
Download review ratings?

### ISSUE THREAD

**Issue by EmilyAlsentzer** [kohler/hotcrp#216]
Is it possible to bulk download the review ratings (e.g "too short") from HotCRP?

**Comment by avandeursen** [comment]
This info is actually available in the "JSON for reviewqualitycollector.org" download option, where for each review it shows as:

```
   "ratings": [
                        "good"
                    ],
```

**Comment by EmilyAlsentzer** [comment]
Oh, perfect. Thanks!
