### ISSUE TITLE
markdown tables in lists -- garbled 

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#218]
When uploading a review containing a markdown table that resides inside a markdown list, e.g.:

<img src="https://user-images.githubusercontent.com/1691795/97522259-04c2af80-19a8-11eb-9c56-272ede403274.png" width="150">

Hotcrp doesn't display it as a table, but rather as regular text:

> <img src="https://user-images.githubusercontent.com/1691795/97522467-8286bb00-19a8-11eb-8733-542e8f355391.png" width="250">

The problem goes away if the table is placed outside the list. 
Placing tables inside lists appears to be legal markdown:

> <img src="https://user-images.githubusercontent.com/1691795/97522652-ef9a5080-19a8-11eb-9332-0cc032d87443.png" width="400">

**Comment by kohler** [comment]
This required moving to a more-CommonMark-compatible Markdown parser but is done.
