### ISSUE TITLE
feature request: honor emoji names when uploading reviews from text files

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#219]
When typing, say, ": scream :" (without the inner spaces) in a text field in hotcrp, one can choose 😱 from a dropdown menu. But when uploading a review from a file that contains this text, it remains as is and the symbol isn't shown. It would be nice if such text---names of emoji---was replaced by the corresponding emoji symbols as part of the upload. 

Thanks,
--Dan

**Comment by kohler** [comment]
Hi Dan, I've been thinking about this for a while and decided not to do it. The risk is that `:smile:` or something be misinterpreted where it wasn't intended. At this point most users have access to emoji keyboards in most applications so hopefully the need is less.
