### ISSUE TITLE
Restrict Registration/Password (Re)Set Ability OR how to properly activate Bulk-created Accounts

### ISSUE THREAD

**Issue by jpennekamp** [kohler/hotcrp#222]
Hi,

we are pretty happy with the features that HotCRP offers. However, recently, we updated our instance and the new version somewhat breaks our established workflow: We only want previously bulk created users, i.e., registered by the PC, to submit papers.

Older HotCRP versions (v2.102):
- We could bulk create users and they would receive their passwords (and immediately have access to their accounts)
- Registration of other users could not be prevented (this was tolerable)

Current HotCRP version (current master):
- We can bulk create users, but this has no effect (no passwords or email are send)
   - **User accounts seem to be only properly created once a password has been set by the user**
   - User information can be send manually, however, this only includes the email
   - Registration/Password reset is only possible if the registration is open (despite the fact that the user accounts are created beforehand)
- With an open registration everyone can register, otherwise nobody can create/activate their account
- Password reset works fine for account WITH a set password (even when the registration is disabled)

Is there a way in current HotCRP versions to
a) Properly create accounts (that are functional even when then registration is disabled), or
b) Allow "registration"/password reset to previously created user accounts only, i.e., disable random account (with different email addresses).

Thanks for your hard work!

Best,

Jan

**Comment by kohler** [comment]
Hi @jpennekamp, it took me a while to figure out what was going on, and I'm not sure I fully have.

* Commit 1c0e97e0ea49e63c9ca58e2aa2bea29b5e23b11b and 6a22034b174d54202cf032729d33057ec7891ed5 has recovered the behavior where email is sent to *all* bulk-created users. In the commit you tested, email was only sent to PC and sysadmin users.
* I am not sure what “only properly created” means. Those users should have been created, even in previous master. What was “improper” about those users? I believe they existed, but had no password yet.

Setting `$Opt["disableNewUsers"] = true` in `conf/options.php` should disable user self-registration, but allow users with existing accounts (or chair-created accounts) to reset their passwords and log in.

**Comment by jpennekamp** [comment]
Hi @kohler, thanks for looking into the issue in detail!

We have now updated our setup and confirmed that the ability to bulk-create users and send password reset links is now restored. So, for our workflow, the issue seems to be fixed! Passwords of bulk-created users can now be set using the link in the email regardless of the self-registration status _(but only using the link in the email)_.

To follow up on your question about "improper" accounts (which still seems to be an issue: Do they really exist properly?): Without a _set_ password, users cannot "manually" set their password, i.e., using the website.  If the user registration is disabled, the user cannot do anything in case he lost the "account activated" email or if the link expired after being bulk-created -- even though the account (apparently) exists in the user list. As a side note, on their own, users have no way of requesting an email to _initially_ set their passwords. Basically, the lack of sent emails resulted in a state where bulk-created non-PC users were shown in the user list, but behaved as if they were not existing. HotCRP's behavior is also consistent even when the registration is enabled as users are prompted to register a new account instead, i.e., it seems that the account in the user list is not detected/found for some reason. Here, users can also freely choose their email address, which should not be the default (or any?) action when _setting_ a (forgotten) password.

While our workflow is restored, using the password set/reset functionality seems to be broken until a password has been set for the first time.

To reiterate, the problem only occurs when users lose their account activation-email AND new-user-registration is disabled, because they cannot (re-)set a password on their own in this case.

I hope this description helps. If you have any further questions, please let me know.

**Comment by kohler** [comment]
> To reiterate, the problem only occurs when users lose their account activation-email AND new-user-registration is disabled, because they cannot (re-)set a password on their own in this case.

I see. That is interesting.

**Comment by kohler** [comment]
I think this is fixed.

**Comment by jpennekamp** [comment]
Fix confirmed. Thanks.
