### ISSUE TITLE
request: in the comments, display reviewer letter after reviewers-anonymity-from-each-other has been lifted

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#225]
In the committee I'm currently a member of, until today, when discussing online the submissions, we referred to each other using letters, rather than by name, as names were unavailable to us. 

Now that this anonymity has been lifted, comments are identified by the name of their authors, but the references inside the comments still use letters, making it cumbersome to identify the associated reviewers (you have to jump every time to the head of the page to check).

Therefore, it would have been helpful if the letter of the reviewer was displayed alongside the reviewer's name for each comment.

Thanks,
--Dan

**Comment by kohler** [comment]
This is done as of 7004608322643602197b2cb94570c97541e5cd64.
