### ISSUE TITLE
Prepare mail fails because of a database error 

### ISSUE THREAD

**Issue by mika-santoro** [kohler/hotcrp#226]
The following error occured when I was trying to prepare mails before sending : "database error: Character set 'utf8_general_ci' cannot be used in conjunction with 'binary' in call to regexp_like".
I found out that the problem was at src/mailclasses.php:233:

`src/mailclasses.php:233:        $where = array("email AS BINARY not regexp '^anonymous[0-9]*\$'");`

This successfully solved the problem:
`$where = array("CAST(email AS BINARY) not regexp BINARY '^anonymous[0-9]*\$'");`

**Comment by kohler** [comment]
Thanks for this report, but in this repository, that code has never contained `AS BINARY`—I suspect that was a local change on your side.
