### ISSUE TITLE
Feature request: Mention PC members / chairs in comments

### ISSUE THREAD

**Issue by avandeursen** [kohler/hotcrp#229]
During the discussion phase, it would be useful if it would be possible to mention the chair or other PC members in comments. For example:

 `@Joe: what you think of ...?`

Then the PC member `Joe` mentioned would receive an email even if he or she is not one of the original reviewers.

For ICSE  2021 we worked with two chairs and seven area chairs: In particular for them it would be helpful. The mechanism can also be used to call for help for extra expertise in the PC for a specific person.

Ideally, the feature would work with some form of completion (as on github), and would be conflict-aware.

Thanks!!

**Comment by kohler** [comment]
This feature is now implemented! If you have experience with it, let me know.
