### ISSUE TITLE
Review requests automatically getting rejected

### ISSUE THREAD

**Issue by kmccurley** [kohler/hotcrp#233]
We run multiple instances of hotcrp on a single server under /confname and we have had several of them report that review requests are getting automatically rejected even though the user who had their review requested had not even logged in. We are unable to reliably re-create this bug, but it has been reported multiple times. The rejection seems to happen within seconds of the review being requested - even before the user tries to login to look at the review that was requested.

I would volunteer to debug this problem myself, but I could not figure out how the state could be changed to refused without the user even logging in.

I'm not sure what session cookies are used for in hotcrp, but since we use multiple instances on a single machine but do not use a shared database for users between the different instances, it's perhaps possible that a cookie is being for multiple conferences. Could that be related to the problem?

**Comment by kohler** [comment]
I believe that you are on an older version of hotcrp, but the current version has a number of changes around accept/decline workflow.

**Comment by kohler** [comment]
(Main commit 85e0c129db63f41033d7439f7317a9e9ae18177b with others before and after.)
