### ISSUE TITLE
Apache HTTPS redirect problems

### ISSUE THREAD

**Issue by asl** [kohler/hotcrp#234]
Apache has some subtle differences as compared to NGINX wrt to redirection. These changes may render HotCRP installation unusable depending on the particular Apache configuration:

1. `HTTPS` environmental variable is not set
2. `SERVER_PORT` variable may return unexpected port value (e.g. 80 instead of 443 for HTTPS connection). The behavior is controlled by `UseCanonicalPhysicalPort` option

I had to introduce few workarounds in order to mitigate these differences (please let me know, if you'd like a PR for them):

1. Check `HTTP_X_FORWARDED_PROTO` variable in addition to `HTTPS`:
```
diff --git a/lib/navigation.php b/lib/navigation.php
index ec12b3e..f6d14c6 100644
--- a/lib/navigation.php
+++ b/lib/navigation.php
@@ -50,9 +50,11 @@ class NavigationState {
             $this->host = $server["SERVER_NAME"];
         }

-        if (isset($server["HTTPS"])
-            && $server["HTTPS"] !== ""
-            && $server["HTTPS"] !== "off") {
+        if ((isset($server["HTTPS"])
+             && $server["HTTPS"] !== ""
+             && $server["HTTPS"] !== "off") ||
+            (isset($server["HTTP_X_FORWARDED_PROTO"])
+             && $server["HTTP_X_FORWARDED_PROTO"] == "https")) {
             $x = "https://";
             $xport = 443;
         } else {
```

2. Special case `$port == 80` and `$xport ==443` (hack!):
```
diff --git a/lib/navigation.php b/lib/navigation.php
index ec12b3e..f6d14c6 100644
--- a/lib/navigation.php
+++ b/lib/navigation.php
@@ -62,7 +64,7 @@ class NavigationState {
         $this->protocol = $x;
         $x .= $this->host ? : "localhost";
         if (($port = $server["SERVER_PORT"])
-            && $port != $xport
+            && ($port != $xport && $port != 80 && $xport != 443)
             && strpos($x, ":", 6) === false) {
             $x .= ":" . $port;
         }
```

Hope this made overall weirdness clear :)

**Comment by kohler** [comment]
This is weird, thanks for pointing it out. I generally recommend Nginx. But I'll take the first change here.

The second is in fact too hacky for me :) although maybe it's OK?…………… I would prefer something based on the presence of a `$server` value.

**Comment by asl** [comment]
> This is weird, thanks for pointing it out. I generally recommend Nginx. But I'll take the first change here.

Yeah, but unfortunately I have no other choice - nginx is not available on our University shared hosting.

The second thing is indeed quite hacky, but I do not see other choice, as Apache can report port 80 instead of 443 for HTTPS connection causing all kinds of problems...

**Comment by kohler** [comment]
Can you set any other variables in the apache config that are passed through fastcgi? Via SetEnv, say?

**Comment by kohler** [comment]
Closing this for lack of communication; feel free to reopen.

**Comment by asl** [comment]
Sorry, I got distracted and forgot to comment. Unfortunately, as this is shared hosting, many things are quite limited. Also, setting some special env variables looks more hacky to me...
