### ISSUE TITLE
PC conflict selection omits top-right dropdown menu at some window widths on Firefox

### ISSUE THREAD

**Issue by tchajed** [kohler/hotcrp#236]
In this screenshot from the paper submission page, there's no dropdown menu for Peterson Yuhala (the top-right person):
<img width="1174" alt="Screen Shot 2021-03-29 at 9 16 50 AM" src="https://user-images.githubusercontent.com/1255037/112842518-3e870780-9067-11eb-9638-69e7eb1f59e5.png">

If you make the window slightly wider, then the bug goes away (the main difference as far as I can tell is that at this width, Rui Yang's affiliation "University of Illinois at Urbana Champaign" no longer wraps):

<img width="1180" alt="Screen Shot 2021-03-29 at 9 19 04 AM" src="https://user-images.githubusercontent.com/1255037/112842680-71310000-9067-11eb-9e34-6ec198b1c8ec.png">

This seems to always happen for the top right entry, so it should be possible to reproduce with a smaller PC.

**Comment by kohler** [comment]
This is clearly a browser bug so at minimum you should say which browser and which width and which site

**Comment by tchajed** [comment]
Ah yes, you're right, sorry for the incomplete report.

I'm on macOS 11.2.3.

I see this bug in Firefox 87 at https://osdi21ae.usenix.hotcrp.com/paper/18 with a width of 1004px (for example) and it goes away at 1065px.

Chrome 89 and Safari 14.0.3 are unaffected.

**Comment by kohler** [comment]
Sounds like you should report this to………………………………Firefox
