### ISSUE TITLE
Batch Paper Submission

### ISSUE THREAD

**Issue by pjattke** [kohler/hotcrp#237]
Hi,
We are using a hosted (*.hotcrp.com) HotCRP instance for simulating a conference as part of our course. Initially, we need to "submit" all papers (~40) that students should review. Is there any way to automate this with scripts, e.g., that take a CSV as input and then create submissions based thereon?

I saw that there is folder `batch/` that provides some scripts to export data. Maybe we could do something similar for the import? However, I guess that these scripts are only locally callable and in our case of a hosted HotCRP this would not be usable anyway?

I appreciate any tips to solve this matter.

Many thanks,
Patrick

**Comment by kohler** [comment]
The batch/savepapers.php script will save papers expressed in JSON format. But part of the deal for free academic hosting is No Support. You don't get access to that script and I won't run it for you.

What you can do is write a script that automates interaction with the HotCRP website, using libcurl or Selenium or etc. If you just try to do this, you might find it a pleasant couple of hours. Then you could post that script.
