### ISSUE TITLE
Withdrawn papers disappear

### ISSUE THREAD

**Issue by JonathanMace** [kohler/hotcrp#238]
This is probably the result of some hotcrp configuration choices on the part of the PC chairs, but:

I'm on a PC and I've submitted some reviews.  After seeing the reviews during the author response period, the authors decided to withdraw the paper.  This resulted in the paper no longer being visible or searchable for me.  The site says I've submited N reviews, but only displays N-1 papers.  It doesn't show up in any search queries for me.  However, if I put the paper number directly into the URL bar, the paper is still visible to me.

Expected behavior?

**Comment by kohler** [comment]
Is the search in “submitted” papers?

**Comment by JonathanMace** [comment]
It affects the following searches:

- `q=&t=s`
- `q=&t=r`
- `q=re%3Ame`
- `q=`

**Comment by kohler** [comment]
`q=&t=r` should include withdrawn papers from now on!
