### ISSUE TITLE
backupdb.sh issue as well

### ISSUE THREAD

**Issue by nc2y** [kohler/hotcrp#240]
This is kind of a sequel of sorts to #239.

`backupdb.sh` also interacts somewhat poorly with recent mysql versions. Specifically, one is to pass `--no-tablespaces` to `mysqldump` unless a `PROCESS` command is used (it is not, in our case; I am actually not sure what it does, but that's besides the point). See: https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html

Proposed patch at: 
https://gist.github.com/nc2y/a1342d6c7bee3f2432e061fe8dbc8e72

Not tested on older versions (although I do believe that mysql 5.7 supported that flag already).

**Comment by kohler** [comment]
Thanks for the bug finds!
