### ISSUE TITLE
Is HotCRP compatible with Apache?

### ISSUE THREAD

**Issue by brad-mengchi** [kohler/hotcrp#241]
Hi all,

Does anyone try HotCRP with Apache? I may not be available with Nginx so I would like to see whether Apache is compatible with HotCRP or not?

Thanks a lot!

Mengchi

**Comment by brad-mengchi** [comment]
And I wonder whether Apache configuration is similar to Ngnix?

**Comment by kohler** [comment]
Some people do use HotCRP with Apache. The README no longer describes Apache configuration because I prefer nginx. If you want, you can use commit history to see some of the old Apache descriptions, or suggest new text.

**Comment by brad-mengchi** [comment]
The .htaccess configuration under HotCRP works fine for me with Apache.

**Comment by kohler** [comment]
@brad-mengchi A pull request with example .htaccess-based configuration might be useful for others.
