### ISSUE TITLE
HTTPS with Apache httpd

### ISSUE THREAD

**Issue by brad-mengchi** [kohler/hotcrp#244]
Hi all,

I set up the HotCRP with Apache httpd. However, I found HotCRP generate URL like http://<web address>:443/<...>. I wonder if I need to set up anything in conf/options.php so that HotCRP will use protocol https with 443, which will make the URL correct?

Thanks!

**Comment by brad-mengchi** [comment]
This problem is similar to https://github.com/kohler/hotcrp/issues/234 but my Apache/2.4.6 (CentOS) PHP/7.2.13 only defines  REQUEST_SCHEME as https, so I have to judge as below in lib/navigation.php:

if ((isset($server["HTTPS"])
             && $server["HTTPS"] !== ""
             && $server["HTTPS"] !== "off")
            || ($server["HTTP_X_FORWARDED_PROTO"] ?? null) === "https"
            || ($server["REQUEST_SCHEME"] ?? null) === "https") {
            $x = "https://";
            $xport = 443;
        } else {
            $x = "http://";
            $xport = 80;
        }

**Comment by kohler** [comment]
I've added a version of this code, thanks
