### ISSUE TITLE
Installing a second two-factor token deletes the first one.

### ISSUE THREAD

**Issue by arthurgleckler** [kohler/hotcrp#246]
I installed a two-factor authentication token — a Yubikey that I'll call A — and saved changes.  I logged out and logged back in with that one, providing a code when prompted.

I installed a second two-factor authentication token as a backup — a different Yubikey, which I'll call B — and saved changes.  I logged out and logged back in, providing a code from B when prompted.

I logged out and tried logging in with a code from A.  That failed.  But a code from B would still get me in.

This means that I can only have one token at a time, which means that I'm stuck if I lose access to one of them.  (I didn't see a way to print backup codes or something like that.)

As a side note, when I switched machines after having set up two-factor authentication, I was able to log in without being prompted for a code at all.  I'm wondering whether that was because I had changed the email address on the account in between.  That's probably a separate issue, but I mention it here just in case there's some relationship between the two problems.

**Comment by kohler** [comment]
Yes, changing account addresses does get around MFA — the MFA information is associated with the original email address.

Sorry for the problem around multiple tokens. I've fixed it, you should be able to add multiple tokens now.

**Comment by arthurgleckler** [comment]
I've just tested it, logging out and logging back in first with one token, then the other.  It works beautifully.

Thanks.
