### ISSUE TITLE
"Act as" is dangerous. Consider changing UI

### ISSUE THREAD

**Issue by kmccurley** [kohler/hotcrp#247]
The "Act as" feature of HotCRP is potentially dangerous in that it may cause information to be leaked. We had an instance today where a program chair clicked on "Act as" inadvertently (or maybe without understanding the consequences). They went on to comment on a paper and the email was sent from the "Act as" person, who did not have rights to see the comments on the paper. 

I'm not sure exactly what the best solution is, but this runs a great risk of having HotCRP leak information to authors who should not be seeing the discussion. I'm not sure exactly how to address this, but I think the UI should make the danger more apparent to program chairs.

One problem is the ordinary view of a paper by a reviewer, where the authors all have a "Act as" glasses icon next to them. I believe that if someone clicks on that, it should show a modal warning that as long as they are acting as someone else, mail will be sent as if from that person. Another option is to make every action that will send mail send a warning to the user if they are acting as someone else. Personally I think the "Act as" function should be only visible on the "Users' view, and the icon should be changed from glasses to something that indicates danger like ⚠️ or even a red color. The display at the upper of "Acting as" should also have a red color on it and a clear way to exist from "Acting as". The way it is right now the only way I can find to stop "Acting as" is to logout entirely or to keep hitting the back button until you get to the place in the history where you started "Acting as". Perhaps Eddie has a better idea of how to handle this in the UI and workflow, but I find it troubling the way it works now.

**Comment by kohler** [comment]
Thanks for the feedback, which I generally disagree with.

**Comment by kohler** [comment]
Some improvements here though; as of latest if you are viewing the site as another user, the upper right looks like this

<img width="568" alt="image" src="https://user-images.githubusercontent.com/410647/128425958-5ca1c50e-fc44-4643-a2d9-cc2ba85372f1.png">

Note that if you click the “Admin” link with glasses, that will return you to your true account.

**Comment by kmccurley** [comment]
That's much better. Thanks.

**Comment by kohler** [comment]
I’m going to close this, Kevin; feel free to reopen if problems remain, but hopefully the new ‘acting as’ UI has been a significant improvement.
