### ISSUE TITLE
Retrieve different versions of papers

### ISSUE THREAD

**Issue by brad-mengchi** [kohler/hotcrp#248]
Hi,

I found out that all paper submissions are recorded in the database, but is there a script/page to retrieve an old version of a paper from the database?

Thanks!

**Comment by kohler** [comment]
If you access an API like the following

https://test.hotcrp.com/doc/hotcrptest-paper18.pdf?fn=history

the resulting JSON will include `link` components by which you can retrieve old versions of papers.
