### ISSUE TITLE
Migrating data between two active hotcrp instances

### ISSUE THREAD

**Issue by snadi** [kohler/hotcrp#249]
Hi @kohler 

As part of the MSR conference, we are running a shadow PC track that is meant to educate next generation researchers on how to review paper (e.g., from [2021](https://2021.msrconf.org/track/msr-2021-shadow-pc?)). The main PC track and the shadow PC track have two different hotcrp sites ([https://msr2022-technical.hotcrp.com/](https://msr2022-technical.hotcrp.com/) and [https://msr2022-shadow.hotcrp.com/](https://msr2022-shadow.hotcrp.com/) respectively) but are under the same conference. We have a couple of questions:

1. Is there a way for us to automatically mirror the paper submissions on the main track to the shadow pc track? Note that the shadow pc track papers may be only a subset of the main track since not authors opt for their paper being reviewed by a shadow pc. Ideally, one of the following options would be great (1) automatically mirroring/migrating all submissions and then deleting those who didn't opt for the shadow pc or (2) adding a tag to the papers on the main track and automatically filtering by that tag and migrating to the shadow pc.

2. Will the conflicts of interest automatically carry over between both tracks? The shadow PC members are different from the main track members. Does it make sense to add the shadow PC members as, for example, external reviewers on the main track such that the authors can declare COI with them as well and then migrate these COI to the shadow PC track or have it automatically reflected there?

Sarah Nadi

**Comment by kohler** [comment]
1. There is no way to automatically mirror submissions. When the main deadline is complete, the main site's administrators can download “JSON with attachments” for all papers that should be ported. You send this large file to me (perhaps via dropbox or whatever) and I can upload it to the named shadow PC site. This takes two weeks notice and reminders.
2. COIs do not carry over automatically. You could add the shadow PC members to the main site's PC, perhaps tagging them as “external” and using Tracks to ensure they get no rights. Alternatively, and perhaps preferably, you could use Assignments > Conflicts and do the job yourself.
