### ISSUE TITLE
Suggestion: allow option to hide scores when opening reviews for rebuttal

### ISSUE THREAD

**Issue by fdouglis** [kohler/hotcrp#250]
I've confirmed with an author that when they were presented with reviews to rebut, the reviews were complete, with scores.  My own preference as a chair would be to allow an option to hide the scores and present only the text.  That way (a) reviewers don't simply say "oh, this person gave me a high score, I don't have to pay as much attention to their comments" and (b) a reviewer who is on the fence can decide later to lower their score without that being obvious to the author.  As it stands, I think such a change would pretty much require an **EDIT**: score lowered because I thought more about _xxx_ addendum.  Which isn't an awful thing, but people won't always do it.  I think simply changing a score silently ... or editing a review without making it clear how it has been edited ... is awkward.  

BTW, while HotCRP runs rings around most other reviewing systems, EasyChair does one thing "right" in that it posts earlier versions of reviews in a way that other reviewers (though not authors) can see the history.  Some way of telling how things change would be nice as well.

**Comment by kohler** [comment]
Scores can already be marked “Hidden from authors until decision”. The administrator can also change the visibility of scores.

**Comment by fdouglis** [comment]
Eddie, I can't find that.  Can you please point me at the setting?  I'd expect it to be here but I'm not seeing it.
![foo](https://user-images.githubusercontent.com/4999923/130619882-9dd97e22-3f9d-43e5-8cd5-dc1f736f6a2c.png)

**Comment by kohler** [comment]
The review field visibility setting is per review field which is on Settings > Review form. There is no universal setting for all scores; in fact at many conferences some scores are intentionally made visible to authors at rebuttal time.

**Comment by fdouglis** [comment]
Thanks, Eddie.  I didn't see it because to get at it I had to expand the field, which was non-obvious.  Since the capability exists, my recommendation/ask would be to annotated the part where you talk about rebuttals, and add a comment there to say that individual fields can be set in that fashion.  Even if this is mentioned in the "guide", having it in the area where the rebuttal is configured would be helpful.
