### ISSUE TITLE
Configuring LDAPS on ldaplogin.php

### ISSUE THREAD

**Issue by karthik-kv** [kohler/hotcrp#258]
Can you please let us know if there an option to configure LDAPS on the ldaplogin.php file. We tried changing using ldap url with the ports exposed for LDAPS, but we are not able to connect and authenticate.

**Comment by kohler** [comment]
I think you have to give an `ldaps://hostname:port/....` URL. Can you try that?

**Comment by kohler** [comment]
Closing for lack of engagement
