### ISSUE TITLE
abstract rendering as plain html text

### ISSUE THREAD

**Issue by jap425** [kohler/hotcrp#259]
Hello,

Using the latest HotCRP from github: HotCRP v3.0b1 [7ea888e...]. We are experiencing that papers abstracts are not rendered as html but as text. The information on the code that is display looks relevant to each paper, so the template and information extraction looks fine, but the html code from the template is showing raw on each paper/abstract page/section. The rest of the HotCRP rendering/functionalities look fine. Wondering if we are missing something on our installation. 

Thank you for your help and for such an amazing project.

**Comment by jap425** [comment]
Hi,
Just to chime something, I update the line 748 on the "src/papertable.php" file, and now the abstract is rendering normal as we expected

            //$fr->value .= ' format0">' . Ht::format0_html($html);
           $fr->value .= ' format0">' . html_entity_decode($html);

JP

**Comment by kohler** [comment]
Hi JP,

I'm closing this as invalid. HotCRP expects abstracts to be text, *not* HTML. It’s not safe to accept arbitrary HTML from users.

Eddie
