### ISSUE TITLE
Swagger/REST API?

### ISSUE THREAD

**Issue by fstrudel** [kohler/hotcrp#260]
I was looking for an OpenAPI spec or a swagger-like generated API for HotCRP.
Is that available? I could not find it by looking at the README or quickly looking at the code.
Thanks!

**Comment by VictorLeP** [comment]
I second the request for an API. Our use case is to automatically post comments to submissions, which would be generated by an external script.

**Comment by yaronhb** [comment]
+1

**Comment by kohler** [comment]
An initial OpenAPI specification is checked in at https://github.com/kohler/hotcrp/tree/master/etc/openapi.json

Documenting the whole API is a significant undertaking, but at least it's begun, so I am closing this issue. Please open additional issues to request more documentation on specifically relevant API calls.
