### ISSUE TITLE
Allow database in InnoDB format

### ISSUE THREAD

**Issue by sjmurdoch** [kohler/hotcrp#27]
InnoDB has some nice resiliency properties when compared to MyISAM, so it would be nice to allow its use.

I'm trying this out by converting my HotCRP test to InnoDB. To do this I first had to drop the FULLTEXT indices because they are not supported in InnoDB prior to MySQL 5.6.4. 

I hacked together some SQL to generate the right SQL for dropping the indices and converting the table. YMMV; do check the output before running it. Replace `<INSERT DATABASE NAME HERE>` with the database name.

````shell
mysql --skip-column-names -B -e "select distinct CONCAT(\"DROP INDEX \", index_name, \" ON \", table_name, \";\") from information_schema.statistics where index_type='FULLTEXT' and table_schema='<INSERT DATABASE NAME HERE>'"
mysql --skip-column-names -B -e "select distinct CONCAT(\"ALTER TABLE \", table_name, \" ENGINE=InnoDB;\") from information_schema.tables where table_schema='<INSERT DATABASE NAME HERE>'"
````

**Comment by kohler** [comment]
Partially addressed; removed fulltext indexes from ContactInfo

**Comment by kohler** [comment]
All fulltext indexes now removed.

**Comment by BecaseWeCan** [comment]
So... anything against using InnoDB? Reliability is kinda highly-valued where I am :)

Also, I saw that MySQL 5.6 has fulltext indexing on InnoDB, so I can even keep those. Do you have a hunch on stuff that may go wrong? Thanks!

**Comment by kohler** [comment]
But where *are* you, Mr. or Ms. Joined April 25, 2015? :)

I don't think the fulltext indexes were super useful and I'm glad they're gone. At this point it would be safe to just change the MyISAM references to InnoDB.

**Comment by kohler** [comment]
Using InnoDB as of aad253215516994a64838bedb313a2fdc99ca4d2
