### ISSUE TITLE
Additional fields for final versions not shown

### ISSUE THREAD

**Issue by vschiavoni** [kohler/hotcrp#270]
Hello,
We are organising the EuroSys'22 Doctoral Workshop (https://eurodw22.hotcrp.com/), and we have the following issue.
We would like authors of final papers to submit, in addition to the final PDF, additional files (2 mandatory, 1 optional).
I've configured our hotcrp instance as follows:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/119208/158990775-b485925c-2c34-4e14-a64f-b0b06877d80a.png">

The problem is: those additional fields are currently only being shown to new submissions, and not to the already submitted ones (that is those for which we need those additional files).
I suspect those additional fields should have been configured before-hand (before submissions were even open): 
is that the case? If new fields are added, those are not shown to previously submitted (and now being finalized) papers?
Is there a workaround ? 

Thanks

**Comment by kohler** [comment]
Thanks for reporting this problem! The issue was a little different—final-version-only document-upload fields were broken. The issue is fixed.
