### ISSUE TITLE
Weird error message (`overAllMerit` missing)

### ISSUE THREAD

**Issue by nc2y** [kohler/hotcrp#273]
I upgraded HotCRP to HEAD (58d5c67... 1M), created a new conference using a configuration file that I'd been using for another conference last year (by conference, I mean a yearly exam that uses HotCRP), and am running into this error on the main page: 

```
/hotcrp/src/pages/p_home.php:243:Home_Page::print_reviews: database error: Unknown column 'overAllMerit' in 'field list' in
select reviewType, reviewSubmitted, reviewNeedsSubmit, timeApprovalRequested, reviewRound, overAllMerit from PaperReview join Paper using (paperId) where (PaperReview.contactId=1) and (reviewSubmitted is not null or timeSubmitted>0)
```
and
```
/srv/hotcrp/src/pages/p_home.php:278:Home_Page::print_reviews: database error: Unknown column 'overAllMerit' in 'field list' in select count(reviewId) num_submitted, group_concat(coalesce(overAllMerit,'')) s01Scores from ContactInfo left join PaperReview on (PaperReview.contactId=ContactInfo.contactId and PaperReview.reviewSubmitted is not null) where roles!=0 and (roles&1)!=0 group by ContactInfo.contactId
```

Examining the schema does indeed indicate `overAllMerit` isn't in the `PaperReview` or `Paper` table, but the funny thing is, it's not either in the older conference I copied this from and this isn't a problem there .

I'm a bit wary of manually altering that table in `mysql` to make this error go away, and I wonder if this is symptomatic of a worse misconfiguration. I am 99% sure I bungled something, but I'd like to understand what, as I need to use this process year-in year-out. 

For full disclosure, I also had to do this: 
```
lib/backupdb.sh -c conf/options-some-different-instance.php -n some-different-instance --pc > /tmp/pc.sql
```
and 
```
mysql this-conf -u this-conf -p < /tmp/pc.sql
```
to dump all of my PC (i.e., the grading profs) into the new db without prompting them to create new accounts. But I doubt this screwed up the database.

Thanks in advance for any help you can provide.

**Comment by kohler** [comment]
Sorry you experienced this. What it sounds like to me is a problematic schema upgrade. Can you please send me at `ekohler@gmail.com` more information, including the configuration file you used, and the output of `lib/backupdb.sh`?

**Comment by kohler** [comment]
Tried to address in 63fef09bcdf4cc2cc95f6eb91da8c1657ebc67ce.
