### ISSUE TITLE
member tag colors have no effect when reviewers are anonymous to one another

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#275]
When discussing a submission, it helps reviewers to know who is going to attend the PC meeting, to make sure that the opinion of those who won't attend is understood/documented. 

Hotcrp administrators typically communicate this information by assigning a different color to the tag that identifies the relevant committee members. But this configuration appears to have no effect when reviewers are anonymous to one another, as shown in the screenshot below, presumably to avoid exposing even this sort of information.

It would therefore be helpful if there was some way to allow administrators to decide that member tag coloring will be displayed to reviewers, even while their names are not revealed. (That said, I understand why one may prefer to avoid adding such support.)

Thanks, Dan.

![hotcrp-screenshot1](https://user-images.githubusercontent.com/1691795/172058243-cee1a7ef-5bea-471c-89dc-e28d2729584c.jpg)

**Comment by kohler** [comment]
Yeah, this is on purpose (anonymous means no information) & doesn't seem high priority to make configurable.
