### ISSUE TITLE
Non-authors receiving another author's paper submission notification email

### ISSUE THREAD

**Issue by ihjkoh** [kohler/hotcrp#276]
Replay steps of the bug:

1. Author 1 submits a paper where Author 2 and Author 3 are co-authors.
2. Author 1 withdraws the paper submitted in step 1.
3. Author 2 submits another paper where Author 4 is the only co-author.
4. Author 1, 2, 3, 4 receive the submission notification email from step 3. 

This bug may be due to reusing some fields in the withdrawn paper slot (e.g., notification emails)

**Comment by kohler** [comment]
Is this happening on a hotcrp.com site?

**Comment by kohler** [comment]
I'm closing this for lack of interaction. If you can provide more details, let me know.
