### ISSUE TITLE
Purpose of the "ready to review" checkbox?

### ISSUE THREAD

**Issue by sylvainhalle** [kohler/hotcrp#277]
HotCRP has a checkbox where authors must mark their submission as "ready for review" for it to be sent to referees. If this checkbox is not ticked by the deadline, the paper is excluded from the reviewing process, even if all fields are completed and a PDF has been uploaded in time.

**Issue 1:** authors are still allowed to make changes to their submission until the specified deadline, even if this checkbox is ticked. Therefore I do not understand its purpose. If it is to spot incomplete submissions (missing PDF or blank fields), HotCRP already detects this by itself and sends a message to the authors.

**Issue 2:** the fact that the submission is still modifiable is only made known to users in a message printed *after* the checkbox is ticked and the changes are confirmed. Users unfamiliar with the system may incorrectly believe this action is irreversible and postpone it until very close to the deadline just in case they want to make last minute changes, with the risk of forgetting.

This is exactly what happened to me for a recent submission to a conference that uses HotCRP. I uploaded a complete submission well before the deadline but waited before ticking the checkbox --and then forgot about it and got my paper rejected (or rather, "not considered for reviewing", which makes little difference on my end).

I find counterintuitive that the default setting is "I upload a paper, but please don't review it", until I explicitly specify that I want it to be reviewed. The organizers of the conference who rejected my paper nevertheless agreed with me that "*the “ready-to-review” feature of hotcrp may be misleading and potentially harmful for authors*" (quote from a private e-mail). This is certainly not in line with other the other conference management systems we are accustomed to, whose behavior is reversed: what you upload **will** be reviewed unless you withdraw.

In my opinion, the system should:

1. Drop this checkbox unless there is a clear situation where it serves a purpose (but I can think of none at the moment)
2. At the very least, send a warning e-mail close to the deadline for all papers that are not marked as ready (along the lines of "are you sure this is what you want?")

**Comment by kohler** [comment]
Hi Sylvain,

It may be that the behavior that inspired this feature is out of date, but some authors have felt that it is very important to prevent a premature paper—or, e.g., a paper uploaded by a junior grad student that a more senior author should verify—from being reviewed. The checkbox is for them. HotCRP aims to have a reasonable default, which is that the checkbox is checked by default, and a warning is shown if a user saves without checking the box. The warning could probably be improved.

I will at least add a message to address issue #2.

Eddie
