### ISSUE TITLE
Problems with shepherding

### ISSUE THREAD

**Issue by scalzava** [kohler/hotcrp#281]
Hi, I have a couple of problems when dealing with shepherding.

1. It seems the "Hide shepherd names from authors" checkbox has been removed from the "Decision visibility" section. Was it dropped accidentally in some release, removed deliberately or just there's something wrong with my configuration?
2. It seems shepherds can only be selected from the list of PC members, not external reviewers. However, it would be great to also include external reviewers, otherwise it might be hard to keep track of papers shepherded by them.

If there's some mistake from my side and can provide assistance, thanks in advance.

**Comment by kohler** [comment]
The option “Show shepherd names to authors” is in the “Shepherds” section,
and is visible.

To allow shepherds to be set to external reviewers, you need to change the
database to enable the `extrev_shepherd` setting.

**Comment by scalzava** [comment]
Dear Eddie, thanks for the quick reply. 

However, I cannot find any "Shepherds" section in the "Settings" tab, not even under the sub-categories. Can you provide more detailed directions on how to reach it?

**Comment by kohler** [comment]
Settings > Decisions.

**Comment by scalzava** [comment]
Dear Eddie, unfortunately there's no Shepherds section under Decisions in my HotCRP installation. I'm using 3.0b1.

Please see the attached screenshot. Any clue on what could be wrong?

![Schermata del 2022-07-27 08-47-04](https://user-images.githubusercontent.com/1430626/181180404-91226305-0f02-48cf-a653-a3d6e6b734a7.png)

**Comment by kohler** [comment]
Please install the Git version & try again/
