### ISSUE TITLE
More descriptive ActionLog for undo/recovery

### ISSUE THREAD

**Issue by kmccurley** [kohler/hotcrp#282]
We had a chair who modified their review form and lost some previous settings. One of the modifications I made to HotCRP is to add an extra field on PaperOption to make an option immutable by the chair, but apparently this event was not covered by it. 

I understand that having a full "undo" capability is probably way out of scope, but I think it would be helpful if the ActionLog showed previous values that were changed - perhaps in the data field. I'm guessing that even that is difficult since I see a record in ActionLog with an `action` field of:
```
Settings edited: topics, msg.conflictdef, options, has_topics```
```
In this case you would have several things changed in a single ActionLog record, so it's not clear how the `data` field would be formatted. Perhaps it would be possible to split this into multiple ActionLog records and record the previous entry with each of them.

On a related note: the use of mysql as a storage medium makes it difficult to use a file-based backup system on top of HotCRP - do you have plans to move settings out of the database?

**Comment by kohler** [comment]
If you want to make a setting unchangeable by the chair, you can declare that setting as `"disabled": true` by modifying `settinginfo.json` or adding an override. For instance,

```
$Opt["settingInfo"] = ["review_form_disabled.json"];

// file review_form_disabled.json:
[
    {"name": "rf", "merge": true, "disabled": true}
]
```

(newer code will prefer `"configurable": false`).

To make an option unchangeable by the chair, declare it as `"configurable": false` in the relevant JSON.

Are you still on your own branch off an old release, or are you up to date?

Can you say more about why settings in the database matters?

**Comment by kmccurley** [comment]
We have other reasons for extending PaperOption, namely to change the UI for options that are specific to IACR. In particular, we show a different kind of required setting for final versions, with a button linking to our external copyright/license system and our system for uploading final versions that is part of the production workflow. Once those actions are completed, we make an API call back to hotcrp to signal that the option state was changed for the paper. We found that building external systems was an easier way to extend hotcrp. We use different CSS and javascript for these settings. 

I was prompted to create this issue only because we had a chair who screwed something up and wanted to restore a form setting. If the ActionLog had more detailed information about what was changed, it would be easier to recover things they screw up. It may not be relevant to your usage on hotcrp.com. The only issue with it being in a database row is that if it was in a file, we could use a file-based backup system to restore the file. I'm not sure how hotcrp caches the settings - that could make it infeasible to store settings in a file.

We are essentially always on an old version, though not as old as the last release 3.0b1 in Nov 2020. Whenever we pull in new code, I have to rewrite the IACR parts of the code (it touches the hotcrp code in only a few places; mostly papertable.php and paperoption.php). The code for hotcrp is changed quite often (as you know!) so we never know when there is a stable version to modify. We tend to have 2-3 instances running at once - they are sometimes on different versions.

**Comment by kohler** [comment]
It might be worthwhile to talk sometime about how you’re extending hotcrp & how to lock down some internal APIs, at least a bit, so that you have an easier time upgrading & so the main code base gets better. Many of the changes in 3.0 were nominally to make hotcrp more extensible, but since ~no one actually publishes their extensions & most of my interactions with the community are bug fixes, I haven’t prioritized that much.

I’m a little surprised you need to extend PaperTable and PaperOption. For new options, it should be natural to *extend* PaperOption, and in the last year a lot of specific stuff was moved out of PaperTable into PaperOptions.

**Comment by kohler** [comment]
(corrected earlier comment to distinguish modifying the superclass and creating a subclass)
