### ISSUE TITLE
review form: issues with changing order of form fields

### ISSUE THREAD

**Issue by bahlgren** [kohler/hotcrp#287]
After updating to version v3.0b3 [1c384f3... 2M], changing the order of review form fields became erratic. The "up" arrow mostly does not work, while the "down" arrow seems to work as intended. Grabbing a field with the mouse sometimes work.

(This is with Firefox 102.0.1)

**Comment by kohler** [comment]
Drag and drop on FF is still a problem, need to adapt to https://bugzilla.mozilla.org/show_bug.cgi?id=505521

**Comment by kohler** [comment]
Thanks for this report! I think 9c5c79e fixes both the arrow issue and the DnD issue; let me know.
