### ISSUE TITLE
Author not included in email notification

### ISSUE THREAD

**Issue by timbrecht** [kohler/hotcrp#291]
For this paper:
https://uwaterloo-cs854-perf22.hotcrp.com/paper/99

The following author was not included in the notification.
Temiloluwa Paul Femi-Gege (University of Waterloo) <[tpfemigege@uwaterloo.ca](mailto:tpfemigege@uwaterloo.ca)>

I had noticed other weirdness (sorry I don't recall the exact details) with this account previously.
But when trying to send the decision notifications this one author was not included (maybe they hyphen causes issues)?

**Comment by kohler** [comment]
Author’s email address as entered into the paper authors

<img width="393" alt="image" src="https://user-images.githubusercontent.com/410647/233076112-17bd5978-548f-40c9-ae3f-d89f29a13e45.png">

Similar but not identical email address taken from Users tab

<img width="621" alt="image" src="https://user-images.githubusercontent.com/410647/233076374-a82e73e9-60bb-4ea5-86e0-ad429034b420.png">
