### ISSUE TITLE
bidding: red x due to a network failure persists until a full page refresh

### ISSUE THREAD

**Issue by JuliaLawall** [kohler/hotcrp#292]
When trying to update bidding scores on a flaky network (say, when several hundred cruise passengers are trying to share a satellite link), the web page appears to be using some kind of dynamic HTML to send updates to the server, and it will annotate
the field with a green checkmark if it is successful, and a red 'x' if it is not successful (say, because of a network timeout).    If you try re-entering the score, the red 'x' never gets cleared and replaced with a green checkmark --- even when the
update is apparently successful.   I noted this when I updated the score for a subsequent paper, which was successful, and then when I reloaded the entire bid scoring page, the field that had the persistent red 'x' was indeed updated.   (Of course
reloading the full page takes even more of the cruise ship's bandwidth, so it's unfortunate that this was the only way to clear the red 'x' and to check to make sure the score update had actually happeend.)

**Comment by kohler** [comment]
This doesn't replicate (failures are replaced with checkmarks on success) so I am closing this issue. But let me offer my most fulsome apologies to your fellow cruise ship passengers for wasting ~40KiB of their satellite bandwidth 😀
