### ISSUE TITLE
Bug: Disparity between client-side and server-side word counts

### ISSUE THREAD

**Issue by josemmo** [kohler/hotcrp#293]
## Description

When using special whitespace Unicode characters, the word count for paper responses shown in the JavaScript UI does not match the count from the plain text view.

## How to reproduce
These screenshots show the word count for the same text containing the repeated string "dummy\u2004text ":

<img src="https://user-images.githubusercontent.com/4470267/214319353-b62c67f3-081b-467c-aa88-61a6020f2702.png" width="460">

<img src="https://user-images.githubusercontent.com/4470267/214321385-76698176-2d43-4987-9591-0f77681a6a32.png" width="460">

## Cause
While the regular expression used for counting words is the same in both "scripts/script.js" (client-side) and "lib/base.php" (server-side), JavaScript and PHP interpret `/\s/` differently. By default, JavaScript also matches Unicode whitespace characters, but PHP merely expands it to `/[\r\n\t\f\v ]/` when the Unicode flag is missing.

**Comment by kohler** [comment]
Thanks for this! Fixed in 26e1df03d. The fix is yours, but since /u is quite a bit slower, there's an extra check.
