### ISSUE TITLE
Uncaught Error:  Navigation::analyze()

### ISSUE THREAD

**Issue by ealtman741** [kohler/hotcrp#296]
Eddie,

I have done an install of the current hotCRP on github to a Centos 7 host running php7.4 and mariadb 10.  The first time I go to my hotCRP site, the page looks like the normal hotCRP welcome page.  However, any reload of the page or navigation from any of the links on the page yields this error:<br>

**Fatal error:** Uncaught Error: Call to undefined method Navigation::analyze() in /var/www/html/lib/navigation.php:581 Stack trace: #0 /var/www/html/index.php(5): require_once() #1 {main} thrown in **/var/www/html/lib/navigation.php** on line **581**<br>

Line 581 is the last in lib/navigation.php and contains this function call:
**Navigation::analyze();**<br>

The **analyze ()** function is defined for the Navigation class, and I am baffled about why this error is being thrown.  *Do you have any ideas?*<br>

The one thing that seems to help marginally is restarting php-fpm:
**systemctl restart php-fpm**<br>

Each such restart lets me do one additional page refresh yielding a "normal" looking welcome page.  Any additional refreshes without a restart yield a new instance of the error above.  (Restarting nginx does not help, nor does manually removing **navigation.php.bin** from opcache.)<br>

I have poured many hours into analyzing this situation, but am stymied and would appreciate any guidance you may have.<br>

Thank you,
Erik Altman
(ealtman@us.ibm.com)

**Comment by kohler** [comment]
Erik, ugh. I have no idea why this might happen. But perhaps it can be coded around, so I got rid of Navigation::analyze() in the latest commit.

Also maybe you should just disable opcache.

**Comment by ealtman741** [comment]
Eddie,

Thanks for this quick reply (as always).  I am looking at coding around as you suggest and will keep you posted.

Thank you,
Erik

**Comment by ealtman741** [comment]
I think the error above occurred due to some strange PHP configuration on my system that was corrupting the $_SERVER$ variable.  I reinstalled on a clean LAMP stack and things now work.
