### ISSUE TITLE
Way to delete all topics in submission form

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#297]
It would be handy to have an option that deletes all topics in https://<conf>.hotcrp.com/settings/subform (similarly to how you can copy all of them together) rather than having to go over them one by one.

My use case: I'm editing them in a text file externally, and, before I was done, I wanted to see how hotcrp groups them using the colon. This was a mistake...

Thanks,
--Dan

**Comment by kohler** [comment]
To delete all settings, go to Settings > Advanced and save the JSON file `{"topic":[]}`
