### ISSUE TITLE
Artifact badge requests are hidden when topics are hidden

### ISSUE THREAD

**Issue by vahldiek** [kohler/hotcrp#300]
Hi,

During the USENIX Security 2023 Fall AE (https://sec23fallae.usenix.hotcrp.com/), we recognized that the available badge (or the first badge the authors select) is hidden when the topics are hidden. 
![image](https://user-images.githubusercontent.com/15247084/230724872-fb19018f-1bbe-458b-910c-3eb94916ec8a.png)
![image](https://user-images.githubusercontent.com/15247084/230724882-fd5ecdac-2c36-4a8a-9274-b941726d7ac7.png)

The culprit seems to be a wrong hierarchy of div tags. 
![image](https://user-images.githubusercontent.com/15247084/230724916-067c7700-d5d3-416e-adb0-e21a742a9fba.png)

Please let me know, if you need additional information. Thanks,
Anjo

**Comment by kohler** [comment]
Hi, just an FYI: to address this problem, and others, I executed a big rewrite of the submission form display order logic. (In 93c59a931a0c29d49af27c31a851536730c37ad4 and other commits.) So you will be able to configure display order more consistently in future conferences.
