### ISSUE TITLE
unable to overwrite affiliation in bulk user creation?

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#301]
Using an online form, we asked committee members who agree to serve to provide their most up-to-date information: first/last name, affiliation, topics, and such. We generated a user csv file accordingly and bulk-created the users. But it seems that this action didn't update name and affiliation, which will require us to ask members, again, to update their information, this time directly in hotcrp. Is this intentional?

**Comment by kohler** [comment]
HotCRP does not allow chairs to update other users' global profiles. I don't plan to change this: users own their global profiles.

CSV upload deferred to users’ global-profile information over information provided by chairs.

It would have been possible for you to update the local names and affiliations one by one, by going to individual users' profile pages. But as of e01bf28fd58cb55a849eeb5eae39b9caad070d6b there is an “Override existing names, affiliations, and collaborators” checkbox on the bulk update page. This will override global-profile information for the current conference.

**Comment by dants** [comment]
Thanks!
