### ISSUE TITLE
Can "Edit submission" be more transactional?

### ISSUE THREAD

**Issue by PeterSewell** [kohler/hotcrp#302]
For a paper with many authors, especially editing their PC conflicts close to a deadline, one can easily end up losing changes.  Is it possible to make this more transactional somehow?  Not sure what would be the best way - perhaps one could grey-out an open edit-submission tab when another user pushes a change?  Or really enforce locking?

**Comment by kohler** [comment]
Something like this is a really good idea. I don't think it wise to gray out edit-submission tabs, people always leave tabs open. Perhaps something like “only apply those changes that the user made”, i.e. if user does not actively edit title, then do not change the saved title.

**Comment by PeterSewell** [comment]
On Wed, 19 Apr 2023 at 13:19, Eddie Kohler ***@***.***> wrote:

> Something like this is a really good idea. I don't think it wise to gray
> out edit-submission tabs, people always leave tabs open. Perhaps something
> like “only apply those changes that the user made”, i.e. if user does not
> actively edit title, then do not change the saved title.
>
Gray out if and when edited by someone else?  I don't know whether that's
feasible.

The parts that caused me trouble were when multiple people were editing PC
conficts check boxes and an other-conflicts text box, where mistakenly I
overwrote and so lost their edits. It would have been good to know that I
should refresh before editing those bits, as those edits can take a while.

peter

**Comment by kohler** [comment]
I'm proposing that HotCRP would only apply changes that the user made.

Example
- You load the page; PC members Alex Aiken and Ellen Zegura are NOT listed as conflicts
- Your coauthor, Bobbi, loads the page; Aiken and Zegura are NOT listed as conflicts
- Bobbi marks Zegura as a conflict, leaving Aiken unchanged, and saves
- You mark Aiken as a conflict, leaving Zegura unchanged, and save

Currently, the system overwrites Bobbi's conflict marking (Zegura is a conflict) with yours (Zegura is not). The proposal would be that HotCRP *ignores* your version of the Zegura conflict, because you did not change that information since loading the page.

**Comment by PeterSewell** [comment]
On Thu, 27 Apr 2023 at 20:38, Eddie Kohler ***@***.***> wrote:

> I'm proposing that HotCRP would only apply changes that the user made.
>
> Example
>
>    - You load the page; PC members Alex Aiken and Ellen Zegura are NOT
>    listed as conflicts
>    - Your coauthor, Bobbi, loads the page; Aiken and Zegura are NOT
>    listed as conflicts
>    - Bobbi marks Zegura as a conflict, leaving Aiken unchanged, and saves
>    - You mark Aiken as a conflict, leaving Zegura unchanged, and save
>
> Currently, the system overwrites Bobbi's conflict marking (Zegura is a
> conflict) with yours (Zegura is not). The proposal would be that HotCRP
> *ignores* your version of the Zegura conflict, because you did not change
> that information since loading the page.
>

Sounds good to me - certainly for the PC conflict and suchlike.  For text
boxes, it's a more interesting problem - I guess in principle HotCRP can
remember the users edit history and do something smart, though I don't know
whether you'd want to go that far.  Maybe just a conventional merge??

**Comment by kohler** [comment]
I've implemented something like this! HotCRP should now report an error if you try to save an out-of-date tab. I think the error messages and behavior post-save-attempt are OK, but do please report if anything goes wrong. Thanks for pointing this issue out.

**Comment by PeterSewell** [comment]
great, thanks!

p
