### ISSUE TITLE
Can't scroll below in-progress edit

### ISSUE THREAD

**Issue by mgree** [kohler/hotcrp#305]
When editing a comment on a paper, you can scroll up (with a very pleasant off-to-the-right reflow of the comment being edited), but you cannot scroll below the comment.

**Comment by kohler** [comment]
Hi, suck. Added this feature yesterday. Which browser are you using? Is your browser taller than your screen?

**Comment by mgree** [comment]
Fixed, thanks! (For the record, it was Firefox 112.0.2 on a conventional landscape screen and browser viewport.)
