### ISSUE TITLE
Reviewform checkboxes are not rendered correctly for single boxes # 7+

### ISSUE THREAD

**Issue by hi-liang** [kohler/hotcrp#306]
https://github.com/kohler/hotcrp/blob/c9cfc87fd80c54c69dc03bcb20e8a748a84f60b3/src/reviewfields/rf_checkboxes.php#L44

When doing bitwise comparison (for checkboxes larger than `MASK2SCORE` range), the `unpack_value_symbols` function should be looping while `$b <= $fval` just like in `unpack_value` above it. 

Currently if we have only box # 7 checked, for instance, the corresponding `$fval` of `64` will never be reached and the checkboxes field returns empty array, rendered as `None`

**Comment by kohler** [comment]
Thanks, fixed in b21da2cd1!

**Comment by hi-liang** [comment]
Great thanks!
