### ISSUE TITLE
CreateDB script: Consider outputting `dbHost`

### ISSUE THREAD

**Issue by EdNutting** [kohler/hotcrp#307]
Hi,

Just had a fun time trying to set up a little test instance of HotCRP inside Docker. One thing that would have helped is if the `createdb.sh` script used the value of the `host` option to output `$Opt["dbHost"] = "....."` to the `conf/options.php` file automatically. Since it does this for the db, db user and db password, it seems like it would be helpful to do it for the db host too.

Cheers,
Ed

**Comment by kohler** [comment]
Thanks for the request!
