### ISSUE TITLE
queries like re:complete<3 don't seem to work correctly inside more complex queries

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#309]
For example:

- Search (re:complete<=0): no papers
- Search formula:(count(OveMer>=0) >= 0): all papers
- Search: formula:( (count(OveMer>=1) >= 1) && (re:complete<=0) ): all papers (should be none)
- Search (re:complete>=0): all papers
- (re:complete>=0) && formula:(count(OveMer>=0) >= 0): no papers (should be all)

**Comment by kohler** [comment]
`re:complete` does not work in formulas

`&&` does not work in search (it should, though, and I'll make it)
