### ISSUE TITLE
"Reviews and comments in plain text" should not truncate for length

### ISSUE THREAD

**Issue by PeterSewell** [kohler/hotcrp#315]
The "Reviews and comments in plain text" button is very useful (as an author) to get a version to save, edit, and archive, and for when the website is not available - but today I see the result contains:

- - - - - Truncated for length, full response available on website - - - - -

which rather defeats the point.  I guess this is just an accident of rendering the response with code that highlights author response beyond a soft limit.  I can't imagine that it's useful - could that truncation just be turned off?

**Comment by kohler** [comment]
This was unintentional — fixed in ff8c8cf89cd5d8c6098e7e0dd297147ec59ea722 — thanks!
