### ISSUE TITLE
`<span class="pavfn">` printed literally on submission page

### ISSUE THREAD

**Issue by VictorLeP** [kohler/hotcrp#319]
On the page of a paper submission on https://sec23winter.usenix.hotcrp.com/ (`https://sec23winter.usenix.hotcrp.com/paper/XX`), a few text items are seemingly wrapped in `<span class="pavfn">` `</span>`, but this is printed literally instead of being used to mark up the text:
![image](https://github.com/kohler/hotcrp/assets/6874341/5a6d24f8-4b09-4e18-839b-57b5533f1ed5)

**Comment by vschiavoni** [comment]
<img width="514" alt="immagine" src="https://github.com/kohler/hotcrp/assets/119208/b2871667-11bf-4bcd-abac-5dc1fd65800a">

Also see in https://middleware2023r2.hotcrp.com
