### ISSUE TITLE
HotCRP reverts case changes in tags (bug?)

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#324]
If I try to modify a tag "Check" (chaptalized) to be "check" (only lowercase letters), when saving, HotCRP undoes my change, reverting the lowercase version to the original capitalized version.

The workaround: remove "Check", save, and only then add "check".

**Comment by kohler** [comment]
This is addressed in a2c54cfea4b435c6ed204bf167e98b96fee289b4. Since tags are not case-sensitive, changes in case were not considered changes at all.
