### ISSUE TITLE
duplicated emails to @named users

### ISSUE THREAD

**Issue by JuliaLawall** [kohler/hotcrp#325]
I had the impression that when a person was named in a discussion message, then they would get one copy of the message by email with a subject line containing Mentioned rather than Comment.  But now (ASPLOS'24) I am getting both, and if my name appears multiple times in the message I get one email for each occurrence.  This leads to  lot of duplicated messages.

**Comment by kohler** [comment]
Hi @JuliaLawall, I think that you must have been getting different messages for different versions of your name—like “@Julia Lawall” vs “@Julia” or something. In 3abb03c45c I reimplemented the mention logic to avoid double-sending. But that was before 10/30 when you created this issue. Are you still seeing duplicate messages for mentions?

**Comment by kohler** [comment]
Never mind, I think I found the bug :( Thanks for reporting it.
