### ISSUE TITLE
request: showing time of comments would be extremely helpful

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#326]
As committees become too large to hold a PC meeting,  _all_ the decisions are made online via HotCRP comments. When the decisions deadline is nearing, program (vice) chairs find themselves spend much of their time on pinging unresponsive reviewers and nudging them to converge.

But because HotCRP comments are only showing date and are missing time, and because there are multiple (vice) chairs, it is frequently hard to decide whether to re-ping an unresponsive reviewer without overdoing it. 

Displaying comment times -- in one's own timezone -- would therefore be very helpful  and very much appreciated.

Thanks,
--Dan

**Comment by kohler** [comment]
Addressed in the above, thanks for the report.

**Comment by dants** [comment]
Thanks!
