### ISSUE TITLE
attachment disappear after editing the comment

### ISSUE THREAD

**Issue by K-Wu** [kohler/hotcrp#331]
Hi there,

Recently, when I modified a comment with an attachment, after I saved the changes, the unchanged attachment disappeared, although during editing, the editor showed the file was still attached. I have to reattach the file by uploading it from my local computer. This is error-prone as it could cause silent missing attachments. Could you please fix it?

Thank you for your support.

Best Regards,
Kun

**Comment by kohler** [comment]
Apologies for this problem, which is fixed. Thank you for reporting it!

**Comment by K-Wu** [comment]
Hi @kohler, no worries. Thanks for this great software and your timely fix! I have one more question: when will this be reflected in the hotcrp.com sites? Thank you again.

**Comment by kohler** [comment]
It is already deployed there

**Comment by K-Wu** [comment]
Sounds good. Thank you!
