### ISSUE TITLE
allow assigning an external reviewer as shepherd

### ISSUE THREAD

**Issue by dants** [kohler/hotcrp#337]
It sometimes happens that an external reviewer is the one who is the most suitable to shepherd. HotCRP currently allows to assign as shepherd the entire PC (including those who haven't reviewed, forming a very long list), but it doesn't allow to assign external reviewers as shepherds. 

It would therefore be helpful: (i) to allow external reviewers to shepherd and (ii) to list the reviewers of the papers at the top of the list of potential shepherds, which will shorten the search.

Thanks,
Dan

**Comment by kohler** [comment]
<img width="505" alt="image" src="https://github.com/kohler/hotcrp/assets/410647/9714ee60-8813-4be3-814d-c136006e33ab">

**Comment by dants** [comment]
Thanks!

**Comment by dants** [comment]
But please notice that this search:

shepherd:<external_reviewer> 

doesn't seem to work, despite the external_reviewer being assigned as shepherd.

**Comment by kohler** [comment]
You didn't check the box, Dan. I can't believe this.

**Comment by kohler** [comment]
<img width="508" alt="image" src="https://github.com/kohler/hotcrp/assets/410647/a3900bab-6329-4a99-9149-0b32d2b292c3">

That is from asplos24spring right now.
