### ISSUE TITLE
Question: possible to delete reviews after submission?

### ISSUE THREAD

**Issue by amytai** [kohler/hotcrp#342]
We currently have a problem where we need to delete a review after it was submitted, because we discovered that the paper violated double-blind policy.

Unfortunately, I cannot figure out how to delete a review after it has been submitted (I tried using the "Assign" feature, but after a review is submitted, it appears I cannot remove the reviewer from the reviewing list).

Thanks!!!

**Comment by kohler** [comment]
Dear Amy Tai (❤️), you can delete a review by going to the review's edit page. Should be a button there to delete it!

**Comment by amytai** [comment]
There it is! Thank you for the fast response.
