### ISSUE TITLE
Anchor links do not lead to specific comments in action log

### ISSUE THREAD

**Issue by VictorLeP** [kohler/hotcrp#345]
In the action log (`/log`), entries are added if a comment is submitted. The entry supposedly has an anchor link to the specific comment: if the entry is "Comment 123 submitted (paper 45)", it links to `https://instance.hotcrp.com/paper/45#cid123`.

However, there is no anchor on the paper page with that specific fragment, so the page does not jump to the correct comment.

Version: v3.0.0 [59e63ca... 1M]

**Comment by kohler** [comment]
This should be fixed, thanks for reporting it!
