### ISSUE TITLE
Authors should be able to tag/mention an unblinded shepherd with '@' in a comment

### ISSUE THREAD

**Issue by 0xabu** [kohler/hotcrp#346]
Basically, this:
<img width="245" alt="image" src="https://github.com/kohler/hotcrp/assets/13037682/c9d1ef58-663e-4e63-902e-9bfa7d845b87">
... it is offering to tag the co-authors and blind reviewers, but not the shepherd.

**Comment by 0xabu** [comment]
It does the right thing in terms of sending the notification when saving the comment, so this bug is *just* about the contents of the suggested completions when typing '@' in the edit box.

**Comment by kohler** [comment]
Thanks Andrew!
