### ISSUE TITLE
Conflicted chair can see reviewers names in comments without override conflict

### ISSUE THREAD

**Issue by vahldiek** [kohler/hotcrp#348]
Hello,

when a chair has a conflict on a paper, reviewer names are not visible:
![image](https://github.com/kohler/hotcrp/assets/15247084/a282a040-7065-46f8-96e1-d430ad02544c)

But they become visible in comments:
![image](https://github.com/kohler/hotcrp/assets/15247084/e5945833-5bef-44c5-a96d-b5bd128b064e)

Is this the expected behavior? Non chair accounts do not see the name (no brackets and name).

I tried looking at the comment/contact code, but couldn't quickly find the place where the logic of pseudonymizing resides. Feel free to point me to it, then I can try to create a path.

Thanks,
Anjo

There seems to be a more general difference:
![image](https://github.com/kohler/hotcrp/assets/15247084/7d6951e6-0f90-4f2b-8c45-b2cf23caa654)
can be deanonymized by clicking:
![image](https://github.com/kohler/hotcrp/assets/15247084/4ce6f386-7bc7-487c-b1a5-f4f3c73e7ddb)

But then I also find comment 5:
![image](https://github.com/kohler/hotcrp/assets/15247084/5e570403-88ac-4e66-b58c-f6b4d6e42de0)

p.s.: This is for https://sec24winterae.usenix.hotcrp.com/

**Comment by kohler** [comment]
Thanks for this report! The issue should be fixed.
