### ISSUE TITLE
Bug: Profile page does not display CoIs textbox

### ISSUE THREAD

**Issue by mod20388** [kohler/hotcrp#349]
The CoIs textbox is not showing in the profile page of any of the HotCRP websites I am registered on.

I have tried accessing the page using different browsers (Firefox, Chrome) and also on mobile. The issue affects an apparently random subset of my co-authors as well.

Here is a screenshot:
![Screenshot](https://github.com/kohler/hotcrp/assets/73276343/d04f7411-d314-4a58-bc14-98d122b33e1f)

**Comment by fdamore95** [comment]
Same issue here.

**Comment by kohler** [comment]
Thanks for reporting this. Although the behavior has not changed recently, I agree that, especially when a conference is collecting collaborators fields, it makes sense to show the per-profile collaborators fields to all users. Fixed.
