### ISSUE TITLE
HotCRP Search function leads to memory leak after `5558a27b295ae9f981ef7a207946fbfea6c7bbb6`

### ISSUE THREAD

**Issue by ichdasich** [kohler/hotcrp#351]
HotCRP after `5558a27b295ae9f981ef7a207946fbfea6c7bbb6` encounters a memory leak when executing an empty search for papers from the main page (clicking search without filling the search box); The HotCRP at hand has ~500 papers, with a ~3GB HotCRP DB and papers being stored in the DB. Memory consumption rises, essentially, eternally (observed up to 40gb, then killed by timeouts).

During the leaking no interaction happens with the mysqld, i.e., this seems to be a PHP internal issue.

System information:
```
OS: Debian 12
PHP: 8.2 (debian 12 default)
Webserver: NGINX with php-fpm
```

Reverting to `5558a27b295ae9f981ef7a207946fbfea6c7bbb6` fixes the issue. Hence, I'd suspect that it is caused by one of the commits revising querying thereafter.

**Comment by kohler** [comment]
Hi, sorry I missed this when you reported it. This issue is fixed in 381615a29fc8a2c5774f1421f9d2128c9c77c087.
