### ISSUE TITLE
Feature request: Scan author-visible comments for violations of single/double-blindedness

### ISSUE THREAD

**Issue by eeide** [kohler/hotcrp#352]
It might be handy to have a "safety check" before author-visible comments are posted that looks for reviewers' names and says, "Your comment appears to contain one or more reviewers' names. Do you really want to post this?"

Context: I've used HotCRP to run a few artifact evaluation committees (AECs) with single-blind reviewing. The members of an AEC are generally PhD students with not a lot of reviewing experience. The AEC process typically includes reviewers posting author-visible comments about things that aren't working (e.g., compilation errors) and authors responding to those comments with clarifications.

More than once, I've had a member of the AEC post a comment in which they identify themselves or another reviewer. E.g.,

> I'm having trouble with X; can you give me some better instructions? With thanks—Joe

> Thank you for addressing @eeide's comment! I had the same problem and now it works for me too.

While a safety check would obviously not be foolproof, it might go some way to catching these sorts of obvious violations of anonymity.

(One could expand the checks I suppose to authors identifying themselves in double-blind situations, but it seems to me that authors are less likely to accidentally do that? I dunno. _My_ pain point is singe-blind AECs.)

(One could also expand the check to reviews I suppose, but again, it seems less likely that there are violations of anonymity there.)

**Comment by kohler** [comment]
I'm not going to make lots of changes here, with the exception of @-mentions, which are automatically anonymized. But I have changed @-mentions so that `@eeide` will be anonymized (before only names and full emails were anonymized).

**Comment by eeide** [comment]
Sounds great; thank you! I did not realize that @-mentions were already anonymized.
