### ISSUE TITLE
Literal HTML character entity sometimes appears for field names in search

### ISSUE THREAD

**Issue by VictorLeP** [kohler/hotcrp#356]
Going to give a concrete example of steps (and a site) to reproduce this bug, because the bug is a bit esoteric:

* Go to https://sec24winterae.usenix.hotcrp.com/search?q=&t=s
* Make sure that under "View options", the checkbox for `"Artifacts Available" badge: Final stable URL` is **off**
* Go to https://sec24winterae.usenix.hotcrp.com/search?q=&t=s again (reload the page)
* Go to "View options"
* Check the box for `"Artifacts Available" badge: Final stable URL`
* Under each paper title, the literal text `&quot;Artifacts Available&quot; badge: Final stable URL:` appears
* The bug is that the literal `&quot;` appears here
* Note that upon reloading the page, the text is correctly shown as `"Artifacts Available" badge: Final stable URL:`

**Comment by kohler** [comment]
Thanks for the report!
