### ISSUE TITLE
Potential configuration path leak.

### ISSUE THREAD

**Issue by peterzheng98** [kohler/hotcrp#358]
Reproduction step:
Access: https://sum3af.hotcrp.com/
Then I can get: `Unable to load configuration file /mnt/hotcrp/main.hotcrp/conf/opt.sum3af.php.`
Although it may not have a significant impact (since the URL itself can prevent special character injection), it seems to reveal the directory structure and could become a potential point of attack. (Maybe using emoji in url?)

**Comment by kohler** [comment]
Thanks for the report!
