### ISSUE TITLE
unable to generate eRights file

### ISSUE THREAD

**Issue by JuliaLawall** [kohler/hotcrp#359]
For EuroSys'25, I have pressed the Submit TOC to ACM button multiple times, but have not received eRights forms on the accepted papers.  Does this require an intervention from the ACM?  Does this require the final versions to already be available?  After the first few times of pressing that button, I still had a box saying "ACM copyright status has changed" and asking to reload.  Clicking on reload just gave back the same box.  Now clicking on Submit TOC to ACM has caused that box to disappear, but I don't know why.  Even if this is an ACM issue rather than a hotcrp issue, it could be useful for the documentation to be more clear about what to so when things go wrong.

**Comment by ekremcet** [comment]
we are facing the same issue with MHV'26. How did you resolve this?
