### ISSUE TITLE
Bug: grace period is not applied

### ISSUE THREAD

**Issue by lucasmaystre** [kohler/hotcrp#51]
Hello,
it looks like 89eddf322fe1dd7ca925f3df3f38870f12d7e464 introduced a bug in the "grace period" feature. We just got hit by this for the ACM COSN conference (https://hotcrp.cosn2015.com/.), running v2.94. Fix is as follows (I don't have time to do proper pull request, etc.)

    diff --git a/src/conference.php b/src/conference.php
    index de01227..f9a9724 100644
    --- a/src/conference.php
    +++ b/src/conference.php
    @@ -984,7 +984,7 @@ class Conference {
                 return false;
             $t = @$this->settings[$name2];
             if ($t !== null && $t > 0 && $grace && ($g = @$this->settings[$grace]))
    -            $t += $grace;
    +            $t += $g;
             return $t === null || $t <= 0 || $t >= $Now;
         }

Behavior until now: `$grace` is a string, so whatever the grace period, nothing gets added to `$t`.

Let me know if you need more details. Best,
Lucas

**Comment by lucasmaystre** [comment]
Just had another quick look, I think this bug might apply to other parts of the code, e.g. `deadlinesAfter`.

**Comment by kohler** [comment]
Thanks! Fixed in 9ad6548.
