### ISSUE TITLE
Bug: Adding ldap user fails by trying to validate username as email address

### ISSUE THREAD

**Issue by croyxz** [kohler/hotcrp#56]
I'm trying to configure hotcrp to use ldap authentication. However, I'm unable to sign in or add any users getting an error. "Database error while adding your account". It appears when I authenticate with an ldap username, hotcrp then tries to validate that username as an email address while adding the account and then promptly fails.  

I tracked this down to lib/login.php: line 137

           if (!($user = Contact::find_by_email($_REQUEST["email"], $reg)))
                return $Conf->errorMsg($Conf->db_error_html(true, "while adding your account"));
Where $_REQUEST["email"] is the username entered on the sign in page.

find_by_email is failing in src/contact.php: line 859

       if (!$reg || !validate_email($email))
            return null;

validate_email is failing because it's taking an ldap username and trying to validate it as an email address.  

$_REQUEST["preferredEmail"] contains the proper email address from the mail attribute in the ldap entry which I think find_by_email was expecting. 

If you have any questions or need more details, please let me know.

**Comment by kohler** [comment]
Try 3354aa2?

**Comment by croyxz** [comment]
It's working as expected now.
Thanks!
