### ISSUE TITLE
Double php suffix (.php.php) showing up in POST URLs

### ISSUE THREAD

**Issue by UlfarErl** [kohler/hotcrp#60]
Still debugging, but am seeing this behavior on a fresh install.

Example URL: 
http://oakland16.hotcrp.org/settings.php.php?group=opt

Pretty sure this is because of .htaccess rewriting, and my current theory is that the underlying problem is that mod_rewrite is actually required---not just a good idea.  (I haven't enabled mod_rewrite yet.)

**Comment by UlfarErl** [comment]
These were actually the URLs being returned from the POST...

I checked out tag v2.97 and did service apache2 restart (instead of reload), and it all works now.

**Comment by kohler** [comment]
Fixed in 00f8135. Thanks for the report; the bug was introduced in e8e806008ef7cede6825f7414cb973ca2fe9975e; your enabling mod_rewrite was what made it work for you.
