### ISSUE TITLE
Bug: can't save reviews of reviews once the numbering starts using special characters

### ISSUE THREAD

**Issue by emeryberger** [kohler/hotcrp#61]
This is a corner case for conferences, to say the least, but I use HotCRP for classes and have students write reviews of papers. Once you have enough reviews, however, the numbering scheme starts adding special characters like "@", and saving reviews of reviews no longer works.

![review error](https://cloud.githubusercontent.com/assets/1612723/10566846/2299dbe6-75c0-11e5-95f7-28df70f784c4.png)

**Comment by kohler** [comment]
Unparse bug (that should say Review #8AA) fixed in c763632683c9997dbba1701efd407e7690cdbb8c

If you still have issues report back
Sigh.

**Comment by emeryberger** [comment]
Just updated. Looks like once we have the weird characters in the review "number", we are stuck...
![screenshot from 2015-10-19 15_10_22](https://cloud.githubusercontent.com/assets/1612723/10588505/83a93f94-7674-11e5-8ad1-fe3f3a1288fe.png)

**Comment by kohler** [comment]
I would expect a reload to fix this. (A reload on the main page.) The “B@” isn't stored anywhere, it's computed from the review ordinal 27, which has not changed in the DB. If you are still having problems, please reopen with instructions to reproduce?

**Comment by emeryberger** [comment]
Reload on main page doesn't help. Looks like an off-by-one error? (Number
scheme goes 8BX, 8BY, 8B@, 8CA...)

**Comment by emeryberger** [comment]
Possible reproduce: enter 52 reviews. Note also that review numbering now goes 8Z, 8BA, 8BB (skipping 8AA).

**Comment by kohler** [comment]
I have now spent a couple hours chasing improvements in bulk review entry so I could enter that many reviews easily and I do not see this bug. I doubt you updated properly and you are in mild trouble.
