### ISSUE TITLE
Log withdrawal of papers

### ISSUE THREAD

**Issue by sharadagarwal** [kohler/hotcrp#70]
I'm running v2.92. The Action log does not show when papers are withdrawn. Please consider adding this action to the log.

**Comment by kohler** [comment]
Hm. Search the log for “Withdrew”. Recent versions log withdraw actions there. I see no reason v2.92 would not have done so. But we are also now at 2.99.

**Comment by sharadagarwal** [comment]
I searched for "Withdrew" and did not find any. I also went to specific time periods where I knew at least two withdrawals happened (one by me) and neither was there.

**Comment by kohler** [comment]
Well, I am finding such log entries on current versions.
