### ISSUE TITLE
minor: multi-conference ajax-added tag link incorrect

### ISSUE THREAD

**Issue by kaytwo** [kohler/hotcrp#72]
When you add a new tag on a paper in a multi-conference installation of hotcrp, the ajax-generated link does not include the multiconference tag, leading to a 404 on clicking the tag.

To reproduce:

1. start a multiconference install
2. submit a paper
3. add a tag to that paper
4. click on the tag after the ajax add but without having reloaded the page

To workaround: F5 after adding the tag - the server-generated tag url will include the correct multiconference url.

**Comment by kohler** [comment]
I think this is fixed, thanks for reporting it!

**Comment by kaytwo** [comment]
:+1:
