### ISSUE TITLE
Option for author peer reviews

### ISSUE THREAD

**Issue by adnia** [kohler/hotcrp#77]
Hello,

what would be the necessary changes to allow for assigning reviews also for authors (non-PC-members)?

I know this is kind of counter-intuitive, but this is our use case: In our seminars, we always use a conference style including anonymous peer reviews. Hence, students must submit one paper and afterwards review two papers of other students.

As I figure making each student a PC member prevents reviewers from always staying anonymous (among the students). Furthermore, we do not want students to be able to decline a review invitation and ideally would like to use auto-assignment of reviews. This means that viewing students as authors as well as external reviewers does not work either, right? Hence my question if it would be possible to assign reviews also to paper authors.

Best regards,
Roman

**Comment by adnia** [comment]
We'll be using external reviewers now and manually assign them. I played around with the external reviewer role and found it to be working, except for the auto-assignment of reviews.

**Comment by kohler** [comment]
That should work. You might also find that “tracks” work for you. Is it possible that your class should be set up like an external review committee: https://test.hotcrp.com/help/tracks
