### ISSUE TITLE
Automated review preference assignment based on deep learning

### ISSUE THREAD

**Issue by mdwelsh** [kohler/hotcrp#78]
Selecting papers to review out of hundreds of submissions is a tiresome and error-prone process. The "topic score" often correlates weakly with my actual interest and expertise in a given paper. Since HotCRP has access to the PDFs, it should be a simple matter to train an AI to automatically assign review preferences based on the actual content of the papers, not just the author-stated topics. I recommend a deep learning network for this. Look forward to seeing this feature in an upcoming HotCRP release - thanks!

**Comment by kohler** [comment]
Yayayyayayayyayayyayayayyayayayayyayyayayyayaya

**Comment by kohler** [comment]
Now please tell me about your family history
https://github.com/kohler/click/issues/243#issuecomment-196596308
