### ISSUE TITLE
Reviewer not shown in "Manual assignment" page when user has no last name

### ISSUE THREAD

**Issue by mwander** [kohler/hotcrp#82]
Steps to reproduce:
- Assign paper review to a user
- Rename last name of user to empty string
- Go to /hotcrp/manualassign

Expected: User listed under "Reviewers"

Actual: List of reviewers does not include user with empty last name

Observed with v2.99.

**Comment by kohler** [comment]
I believe this issue has been fixed in HEAD; at least I cannot replicate it.

**Comment by mwander** [comment]
Can confirm, it's fixed in HEAD. Thanks!

**Comment by kohler** [comment]
Glad to hear it!
