### ISSUE TITLE
Allow PC to view conflicts without viewing authors

### ISSUE THREAD

**Issue by phil-levis** [kohler/hotcrp#83]
(in the OSDI PC meeting now)

It seems like PC members can't view the conflicts on a paper. While this restriction makes sense during the review process, it's problematic in the meeting itself. E.g., you don't know if the person sitting next to you is a conflict on a paper so you shouldn't look through the reviews. The information is revealed anyways, when the chairs put the papers up for discussion. It would be nice to have a way for PC members to see the conflicts.

If this is possible, sorry! Several of us searched through the settings pages and couldn't find it, and it looks like the source code is 

    function can_view_conflicts(PaperInfo $prow, $forceShow = null) {
        $rights = $this->rights($prow, $forceShow);
        return $rights->allow_administer
            || $rights->act_author_view
            || (($rights->allow_pc_broad || $rights->potential_reviewer)
                && $this->can_view_authors($prow, $forceShow));
    }
?

**Comment by kohler** [comment]
This setting has changed back and forth several times over the years and no single choice seems satisfactory. I've even had requests like "hide conflicts from light PC" (before the current hide became default). Would "show conflicts on tracker" be enough?

**Comment by phil-levis** [comment]
Show conflicts on tracker would help, especially if the chairs cluster papers on related topics. It does seem like something which chairs might want to configure.

**Comment by phil-levis** [comment]
The tracker and timer are a nice feature, by the way (first time I've seen them used)!

**Comment by kohler** [comment]
See e24c8bf7114227b92b117cf009eead931a7d54c4, ebde411d0acbd4d1b5d0648e411032ce59760261

**Comment by phil-levis** [comment]
The OSDI program committee all broke out laughing in disbelief when they found you've already rolled out the feature. Thank you!

**Comment by phil-levis** [comment]
When we realized that it only turns on while the meeting tracker is running, Jeff Chase said "It's beautiful!"

(comment added because Rebecca said some people outside the meeting are drawing amusement from the thread)
