### ISSUE TITLE
Send mail to PC members stuck after the first email

### ISSUE THREAD

**Issue by yqzhang** [kohler/hotcrp#84]
First of all, thanks a lot for maintaining the software and it is very helpful.

We use version 2.100 for CGO 2017, and we are having issue sending emails to the PC members. Whenever an email is sent to multiple people through hotcrp, only the first recipient (sorted alphabetically based on the email address) gets the email. The send email page will stuck at the following state, and the rest of the recipients never receive anything. All the emails other than the first one don't even get to `/var/log/mail.log`.

![image](https://cloud.githubusercontent.com/assets/2654106/17494818/61312d3a-5d84-11e6-9fc7-c4723b3fa2cd.png)

Could you help me take a look at this? Thank you!

**Comment by kohler** [comment]
I’m afraid I can’t provide much support since you aren’t using hotcrp.com.

The first thing to check is whether PHP is stopping with an error, or whether the mailer is blocking.

How many of the emails show up in HotCRP's action log?

To check if PHP is stopping with an error, ensure your PHP is configured to print errors to the log (e.g., `log_errors On` and `error_reporting E_ALL & ~E_DEPRECATED`), then check the log. Sadly not all errors are actually printed there, but many will be.

Another way is to add `error_log("about to send")` to `mail.php` `send_prep` function. Add more log statements to similar functions. Does the `Mailer::send_preparation` function ever return?

**Comment by yqzhang** [comment]
This happens when I tried to send emails to all PC members, which translates to ~40 emails in total. In the action log, it says `Sending mail #1 "[CGO 2017] Welcome, submission site and hotel info`.

**Comment by kohler** [comment]
Now check the PHP log as I suggested. Does the `Mailer::send_preparation` function ever return?

**Comment by samguyer** [comment]
Can you send any email at all? I found that my sys admin people were
blocking certain kinds of incoming and outgoing traffic.

Definitely check logs, though, as Eddie suggested.

-Sam

**Comment by yqzhang** [comment]
I checked `/var/log/mail.log` and only one out of the ~40 emails is being sent through the mail app, so it is probably stuck in hotcrp. I will need to get the proper permission from the university in order to debug this, so probably won't be able to do this tonight. Hopefull, I will get the permission tomorrow morning. I'll definitely keep you guys posted on this though. Thanks a lot for the help!

**Comment by yqzhang** [comment]
So the issue was caused by the fact that the university disabled `pcntl_wifexited()` and `pcntl_wexitstatus()` in `php.ini` for security reasons. As a result, the mailer failed at [line 528](https://github.com/kohler/hotcrp/blob/master/lib/mailer.php#L528) for undefined calls.

**Comment by samguyer** [comment]
You might find other issues like this one as you use more of the features.
On my system, for example, there are a lot of network filters for
"suspicious" URL patterns, like anything containing the word "password".
 -Sam

**Comment by yqzhang** [comment]
I ended up switching back to the php mailer instead. I think maybe we could warn user when they are using the internalMailer when these functions are not presented, or fall back to the php mailer when such exception occurs.

**Comment by kohler** [comment]
The `lib/base.php` file provides alternate definitions for `pcntl_wifexited` and `pcntl_wexitstatus` if they are not defined. But disabling these functions *leaves them defined.*

Your university should not disable those functions, their definitions are trivial and not security sensitive. (You can see their equivalents in `lib/base.php`.)

**Comment by yqzhang** [comment]
Yea, I agree. Thanks a lot for the help and I'm going to close this then.
