### ISSUE TITLE
Y2038 issue

### ISSUE THREAD

**Issue by emeryberger** [kohler/hotcrp#85]
To reproduce, enter a date way into the future. It will end up as January 2038.

Fix is here (either use DateTime or possibly just a 64-bit compile):
http://stackoverflow.com/questions/5319710/accessing-dates-in-php-beyond-2038

**Comment by emeryberger** [comment]
(let me add, clearly no rush...)

**Comment by kohler** [comment]
let me just drop everything and get right to this

**Comment by emeryberger** [comment]
hey, time flies.

**Comment by kohler** [comment]
(it's not a simple fix; we use unix timestamps in the DB)

**Comment by emeryberger** [comment]
ugh

**Comment by kohler** [comment]
This might be fixed, at least on 64-bit PHP installs; current HEAD has a migration that makes the unix timestamp DB columns bigints (i.e. 64 bit).

**Comment by kohler** [comment]
If it's not fixed reopen!
