### ISSUE TITLE
Amnesiac iteration context

### ISSUE THREAD

**Issue by PeterSewell** [kohler/hotcrp#89]
When iterating through my reviews using the right-triangle "next" button on the individual paper pages, if I leave the browser window alone for some time (hours), it appears to forget the context and switch to iterating through all submissions.   Minor, but a little awkward and quite bizarre.

**Comment by kohler** [comment]
Peter, which site is this?

**Comment by PeterSewell** [comment]
PLDI 2017, https://pldi17.hotcrp.com/

**Comment by kohler** [comment]
Boo. I was hoping it was a non-hotcrp.com site

Each page remembers the list it's on, and then sets a cookie immediately before page unload containing the list. The cookie lets the server can repeat the list on the next page. Without a cookie the list would be included in the URL, which sucks. But I thought the code was working.

Any chance you were logged out in the interim?

**Comment by PeterSewell** [comment]
On 5 January 2017 at 22:09, Eddie Kohler <notifications@github.com> wrote:

> Boo. I was hoping it was a non-hotcrp.com site
>
> Each page remembers the list it's on, and then sets a cookie immediately
> before page unload containing the list. The cookie lets the server can
> repeat the list on the next page. Without a cookie the list would be
> included in the URL, which sucks. But I thought the code was working.
>
> Any chance you were logged out in the interim?
>
I didn't get the "you have to sign in again" page inbetween, but maybe the
browser can sometimes automatically and invisibly sign me back in??   It
all works fine normally, so there must be something timing out somewhere.

p

**Comment by kohler** [comment]
To be clear: If this happens again, please let me know, and thanks for reporting the problem!

**Comment by PeterSewell** [comment]
happened again, I'm afraid.  Same PLDI17 site.   I was going through "my
reviews", adding comments for some, and at the end it flipped to going
through "submitted papers", with the successor to my last review-assignment
paper.  No long delay, no re-log-in.

best,
Peter

**Comment by kohler** [comment]
I raised a cookie timeout from 2sec (should be enough, but perhaps vulnerable to slow connections and [depending on stuff I don't know] timestamp skew) to 20sec. Maybe that will help?

**Comment by kohler** [comment]
Peter, have you experienced any more amnesia?

**Comment by PeterSewell** [comment]
haven't used it for a little while now.  I think I did, but wouldn't bet on
it - sorry for not paying more attention
