### ISSUE TITLE
UX: zebra stripe the topic preference list

### ISSUE THREAD

**Issue by kaytwo** [kohler/hotcrp#92]
![2017-01-17-151353_1440x2560_scrot](https://cloud.githubusercontent.com/assets/587187/22040267/e595bb82-dcc7-11e6-866c-5ccaf7c63f5c.png)

Somewhat minor, but this table could really use some zebra striping so I don't accidentally hit "high" for embedded systems security on accident.

If I get a spare moment I'll send a PR.

**Comment by kohler** [comment]
Addressed in 98637374ede9d2cd8ba32f265daa75bd68238c3a
